### ISSUE TITLE
Add option to build without editor 

### ISSUE THREAD

**Issue by Ludea** [adamrehn/ue4-docker#10]
For improve size of images for Ci, I think I could be interesting to add an option to take off the build of editor.

So directx and Vulkan librairie are no longer useful too. 

The goal of my Ci is to build only the project, by cli not launch editor

**Comment by adamrehn** [comment]
The `UE4Editor` executable is required for a number of key build-related tasks supported by the Docker images, including cooking project content, packaging projects, and [running automation tests](https://github.com/adamrehn/ue4-docker#running-automation-tests). It cannot be removed without adversely affecting the functionality of the containers.
