### ISSUE TITLE
Textures not visible correctly for 4.25.3 with OpenGL 

### ISSUE THREAD

**Issue by meetakshay99** [adamrehn/ue4-docker#107]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.69 (latest available version is 0.0.71)
Operating system:           Linux (Ubuntu 18.04.4 LTS, 5.4.0-1025-aws)
Docker daemon version:      19.03.12
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       155 GiB
Total system memory:        30.91 GiB physical, 0 bytes virtual
Number of processors:       4 physical, 8 logical

```

The textures are not visible correctly when building an app with _-opengl4_ param in a docker for Unreal Engine 4.25.3. The textures are all blue and black in color.
Following are the changes I did:
1. Updated the BaseEngine.ini file to comment Vulkan and enable OpenGL
_[/Script/LinuxTargetPlatform.LinuxTargetSettings]
; When neither -vulkan nor -opengl4 are passed on the command-line, the engine will default to the first targeted RHI.
; +TargetedRHIs=SF_VULKAN_SM5

; OpenGL4 is deprecated, you can comment this back in to add it to your targeted RHI list
+TargetedRHIs=GLSL_430_

2. Commented this line of code at _https://github.com/EpicGames/UnrealEngine/blob/4.25.3-release/Engine/Source/Runtime/RHI/Private/Linux/LinuxDynamicRHI.cpp#L81_ so that the message dialog box for OpenGL deprecation is not presented.
_FMessageDialog::Open(EAppMsgType::Ok, NSLOCTEXT("LinuxDynamicRHI", "OpenGLDeprecated", "Warning: OpenGL is deprecated, please use Vulkan."));_

3. Run the app with _-opengl4_ param.

The resulting output is not as expected. The textures are all blue and black in color.

**Comment by Jggggg** [comment]
Did u build successfully on Ubuntu?

**Comment by meetakshay99** [comment]
> Did u build successfully on Ubuntu?

Yes, 4.25.3 docker could be built fine.

**Comment by Jggggg** [comment]
and could u tell me what changes u modify and how to run it

**Comment by Jggggg** [comment]
> > Did u build successfully on Ubuntu?
> 
> Yes, 4.25.3 docker could be built fine.

I find 4.25 and 4.24 r different from 4.23. So I dont know how to modify it . I just move 4.23 pixelstreaming to 4.24

**Comment by adamrehn** [comment]
@meetakshay99 does this issue occur when building and running your application directly on a Linux host system, or only when using containers?

**Comment by meetakshay99** [comment]
It had occurred on both - host system as well as the container.

**Comment by adamrehn** [comment]
In that case, it sounds like an upstream issue to raise with Epic Games rather than something related to ue4-docker. Although I suspect you won't get any action from them on this, given that [OpenGL support was recently removed for all desktop platforms in Unreal Engine 4.26.0](https://docs.unrealengine.com/en-US/WhatsNew/Builds/ReleaseNotes/4_26/index.html#removed:opengldesktoprendering).
