### ISSUE TITLE
Chocolatey fails to install windbg

### ISSUE THREAD

**Issue by dkmartov** [adamrehn/ue4-docker#109]
Hi Adam and Co.!

```
ue4-docker version:         0.0.71 (latest available version is 0.0.71)
Operating system:           Windows 10 Pro Version 1903 (OS Build 18362.1139)
Docker daemon version:      19.03.13
NVIDIA Docker supported:    No
Maximum image size:         200GB
Available disk space:       556.96 GiB
Total system memory:        31.95 GiB physical, 37.49 GiB virtual
Number of processors:       6 physical, 12 logical
```

I am trying to build the ue4 image in a windows container from my own vanilla fork of the engine using the command
ue4-docker build  -repo=MYREPO -branch=release

However I am getting an error when chocolatey tries to install windbg. This error ends the build process. It could be that the download location for windbg has changed. Attempting a separate install on my local machine with chocolatey also fails. 

Below is the copy paste of the relevant output from the installer. Does anyone have a workaround for this?

Chocolatey v0.10.15
Installing the following packages:
windbg
By installing you accept licenses for the packages.
Progress: Downloading windbg 10.0.10586.15... 100%

windbg v10.0.10586.15 [Approved] - Likely broken for FOSS users (due to download location changes)
windbg package files install completed. Performing other installation steps.
Attempt to get headers for http://download.microsoft.com/download/6/A/2/6A2ECE81-C934-4E47-91CC-52DA00A65345/Installers/e8bc712abeffd7c9711ee3f55d4aa99b.cab failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://download.microsoft.com/download/6/A/2/6A2ECE81-C934-4E47-91CC-52DA00A65345/Installers/e8bc712abeffd7c9711ee3f55d4aa99b.cab'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading windbg
  from 'http://download.microsoft.com/download/6/A/2/6A2ECE81-C934-4E47-91CC-52DA00A65345/Installers/e8bc712abeffd7c9711ee3f55d4aa99b.cab'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://download.microsoft.com/download/6/A/2/6A2ECE81-C934-4E47-91CC-52DA00A65345/Installers/e8bc712abeffd7c9711ee3f55d4aa99b.cab'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of windbg was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\windbg\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - windbg (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\windbg\tools\chocolateyInstall.ps1'.
 See log for details.
The command 'cmd /S /C choco install -y windbg && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.' returned a non-zero code: 404
[ue4-docker build] Error: failed to build image "adamrehn/ue4-build-prerequisites:1903".

Thanks!

**Comment by adamrehn** [comment]
Duplicate: #92
