### ISSUE TITLE
200GB doesn't seem to be enough space on Windows as of UE4 4.25

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4-docker#112]
Breaking out of https://github.com/adamrehn/ue4-docker/issues/99#issuecomment-722467345 for visibility: It seems like the 200GB sandbox size in the `ue4-docker setup` and manual Windows 10 instructions is not large enough for UE 4.25.

Experiments and user reports in #99 suggest that even 400GB might not be sufficient, but 600GB has been successful.

The largest intermediate layer in my (incomplete) build of ue4-minimal on Windows 10 2004 is 263GB, with nothing excluded. I didn't watch closely enough to observe a peak disk usage. I expect all subsequent layers in the build to be smaller, as this is the last state of the "builder" target, before we start using `COPY --from=builder` to assemble the clean final image.

Since free disk space inside is limited by the free disk space on the host drive, setting this too high doesn't seem too risky, as you cannot over-commit. At worst, you would fill your hard disk, the build fails, and then Docker cleans up all the temp stuff and you're back to simply low on disk space.

**Comment by dkmartov** [comment]
Out of curiosity do you think this is the same error I am getting in #110 ?
I would be good if the community who was working on this had a discord or something. I can make one and make Adam mod if people are interested.

**Comment by TBBle** [comment]
Replied on that issue.

**Comment by adamrehn** [comment]
@TBBle agreed. I've bumped it to 400GiB in commit a29ae6c and updated the docs to match. Once all of these frustrating filesystem bugs are resolved for Windows containers and things can be tested properly without risk of conflation then we can re-assess and determine whether 400GiB is sufficient or if it needs to be bumped further.
