### ISSUE TITLE
Can you plz have python3-dev to linux docker build ? 

### ISSUE THREAD

**Issue by Kiddinglife** [adamrehn/ue4-docker#113]
It might make sense to get python3-dev added to the ue4-full image on Linux. I believe that the Windows builds already have the equivalent present, so this makes sense to me.

**Comment by TBBle** [comment]
Given we install `build-essentials` and `python3` in the pre-requisites image, it makes sense to me to install python3-dev there as well, so that any `pip`-installed packages with extensions but no compatible wheels can be installed.

**Comment by adamrehn** [comment]
Sounds reasonable to me.
