### ISSUE TITLE
Failed compiling for windows (4.25.4)

### ISSUE THREAD

**Issue by muit** [adamrehn/ue4-docker#117]
Hi!
Thanks for your awesome work :)

Output of the `ue4-docker info` command:
```
ue4-docker version:         0.0.72 (latest available version is 0.0.72)
Operating system:           Windows 10 Pro Version 2004 (OS Build 19041.630)
Docker daemon version:      19.03.13
NVIDIA Docker supported:    No
Maximum image size:         200GB
Available disk space:       540.69 GiB
Total system memory:        31.92 GiB physical, 36.97 GiB virtual
Number of processors:       8 physical, 16 logical
```

I did build ue4-mininal and ue4-full for linux no problem, but now building the linux images I get a compiler error I've never seen before. I though maybe you knew what it could be.
Engine version is 4.25.4.

```
Module.MeshUtilitiesCommon.cpp
c:\unrealengine\engine\source\runtime\core\public\containers\containerallocationpolicies.h(425) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'd:\a01\_work\39\s\src\vctools\compiler\utc\src\p2\main.c', line 187)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information


... in another try I got a similar one:

[30/57] Module.Core.9_of_14.cpp
    c:\unrealengine\engine\source\runtime\core\private\misc\outputdevicefile.cpp(381) : fatal error C1001: An internal error has occurred in the compiler.
    (compiler file 'd:\a01\_work\39\s\src\vctools\compiler\utc\src\p2\main.c', line 187)
     To work around this problem, try simplifying or changing the program near the locations listed above.
    Please choose the Technical Support command on the Visual C++
     Help menu, or open the Technical Support help file for more information
```

[DockerBuild.log](https://github.com/adamrehn/ue4-docker/files/5632122/DockerBuild.log)

**Comment by adamrehn** [comment]
Hmmm, that's a new one. There's a [different error](https://docs.adamrehn.com/ue4-docker/building-images/troubleshooting-build-issues#building-the-engine-in-a-windows-container-fails-with-the-message-fatal-error-c1060-the-compiler-is-out-of-heap-space) that I know crops up when the host system's pagefile isn't large enough, and the mention of *"simplifying or changing the program near the locations listed above"* makes me think that this could potentially be a memory-related issue too. Can you please try increasing the pagefile size by 10GiB (remembering to reboot to apply the changes) and running the build again to see if it makes any difference? If that doesn't help then I can only assume it's a legitimate bug in the Microsoft Visual C++ compiler.

**Comment by muit** [comment]
mmm Increased it from 15GB to 25GB, still fails to compile. I also noticed the places where you get this error are random.

Just for context, on the host machine I am able to build and never saw this error. I will get a windows server soon so this issue may not happen to me anymore but, its still unfortunate.

**Comment by adamrehn** [comment]
Are you using the same compiler version on the host system as the one inside the container? It's possible that this is an actual bug in MSVC that subsequently got patched (or worse, that got introduced, if your host compiler version is older than the container rather than newer.)

**Comment by muit** [comment]
humm

My root system is using Visual Studio 2019 14.24.28316 toolchain and Windows 10.0.18362.0 SDK.

On the docker container, Visual Studio 2017 14.16.27045 toolchain and Windows 10.0.17763.0 SDK. Also MSBuild's version there is 16.8.2+25e4d540b.

**Comment by adamrehn** [comment]
Okay, it might be worth re-building your `ue4-build-prerequisites` image so it uses a newer compiler version. I built a [fresh image](https://hub.docker.com/layers/adamrehn/ue4-build-prerequisites/20H2/images/sha256-d621f3faa3f0c6c48c732582eb57f45d2cac3eccfb882f0b6dc519b5a36bf61a?context=explore) over the weekend (which contains Visual Studio Build Tools 2017 version 15.9.28307.1321 according to [`Get-VSSetupInstance`](https://github.com/Microsoft/vssetup.powershell) and Windows 10 SDK version 10.0.17763.0 according to its `SDKManifest.xml` file) and that was able to compile both Unreal Engine 4.25.4 and 4.26.0 successfully.

**Comment by muit** [comment]
Building 4.26 right now, so far it has passed compilation and is doing shaders now so good sign!

**Comment by muit** [comment]
Since I changed the cpu I have a ton of (expected) weird issues with compilation. Will follow up on this after I have reinstalled a couple of things :)

**Comment by muit** [comment]
This build passed after getting lastest prerequisites and updating windows to 20H2
