### ISSUE TITLE
Clarify oldest supported UE4 version

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#134]
[README](https://github.com/adamrehn/ue4-docker/blob/master/README.md) says:
> Unreal Engine 4.20.0 and newer is supported.

On the other side, [this page](https://docs.adamrehn.com/ue4-docker/use-cases/continuous-integration) says:

> Minimum UE4 Version | 4.19.0

[This page](https://docs.adamrehn.com/ue4-docker/read-these-first/introduction-to-ue4-docker) also says

> Unreal Engine 4.19.0 and newer is supported.

**Comment by adamrehn** [comment]
Apologies for the discrepancy there! Older versions of ue4-docker supported Unreal Engine 4.19.x, but support was subsequently dropped in commit 57a600a (live in ue4-docker version 0.0.78) which facilitated simplification of the Dockerfiles that ship with ue4-docker. As of today, Unreal Engine 4.20.0 is the oldest supported version. I'll update the documentation to reflect this as soon as the current GitLab outage is resolved (the docs are hosted on GitLab Pages) and close this issue once I've done so.

**Comment by adamrehn** [comment]
Right, the docs are now updated.
