### ISSUE TITLE
Packaging project fails if missing write permission to /home/ue4/UnrealEngine

### ISSUE THREAD

**Issue by RoryDungan** [adamrehn/ue4-docker#141]
Output of the `ue4-docker info` command:

```
ue4-docker info
ue4-docker version:         0.0.79 (latest available version is 0.0.81)
Operating system:           Linux (Fedora 30 (Workstation Edition), 5.3.7-200.fc30.x86_64)
Docker daemon version:      19.03.12
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       1.52 TiB
Total system memory:        31.17 GiB physical, 0 bytes virtual
Number of processors:       4 physical, 8 logical
```

Additional details:

- Are you accessing the network through a proxy server? **No**

-----------------------------------

Hi! I'm using ue4-docker for containerised builds on Jenkins. The Jenkins Docker plugin always runs containers with this command: 
```
docker run -t -d -u 570896598:570800513 -w /var/jenkins/workspace/dev_game_test -v /var/jenkins/workspace/dev_game_test:/var/jenkins/workspace/dev_game_test:rw,z -v /var/jenkins/workspace/dev_game_test@tmp:/var/jenkins/workspace/dev_game_test@tmp:rw,z
```
The arguments after `-u` mach the _host_ user and group ID, and `dev_game_test` is replaced with the Jenkns job name. The user seems to be set to that in order to ensure that the container has write permission to the mounted volume so that it can save build artifacts there. However, this means that since we aren't running as the `ue4` user any more we lose write permission to `/home/ue4/UnrealEngine`. 

This shouldn't cause any issues, since it's normal to run programs from a read-only directory. However, the way that the ue4-docker images are set up, UE4 will actually set up a bunch of symbolic links to Mono DLLs inside `/home/ue4/UnrealEngine/Engine/Binaries/ThirdParty/Mono/Linux`, as well as compile some DLLs inside `/home/ue4/UnrealEngine/Engine/Intermediate/Build/BuildRules` the first time it needs to run the UnrealAutomationTool. 

On a fresh image, `Engine/Binaries/ThirdParty/Mono/Linux/lib/mono/4.5` won't contain any DLLs (or links to DLLs). It should contain links to all the System*.dll files from the folder for the more specific version of Mono, but this will be set up automatically when you call `RunUAT.sh` because that in-turn[ calls `SetupEnvironment.sh`](https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Build/BatchFiles/RunUAT.sh#L65), which [then calls `SetupMono.sh`](https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Build/BatchFiles/Linux/SetupEnvironment.sh#L23), which then [calls `FixMonoFiles.sh`](https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Build/BatchFiles/Linux/SetupMono.sh#L10) which [creates all the symbolic links](https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Build/BatchFiles/Linux/FixMonoFiles.sh) necessary. We can fix this by running `SetupMono.sh` once as the `ue4` user before trying to make any builds as any other users.

Once I got Mono working, I uncovered another issue which was that `Engine/Intermediate/Build/BuildRules/UE4Rules.dll` was missing. This file appears to ship with versions of UE4 from the Epic Games Launcher but once again, on source builds for Linux it seems to be auto-generated on first run. The easiest way I found to generate this file was to run `UnrealBuildTool.exe` once with the `UE4Game` target. Once it has been generated, it'll never need to be modified again, meaning that the UE4 installation can now work as fully read-only!

To work around these issues, I've created my own Dockerfile based on the default `ue4-full` image:
```
FROM ue4-docker.artifactory.bigworldtech.com/ue4-full:4.26.1-opengl
RUN bash -c "source /home/ue4/UnrealEngine/Engine/Build/BatchFiles/Linux/SetupMono.sh /home/ue4/UnrealEngine/Engine/Build/BatchFiles/Linux && \
        mono Engine/Binaries/DotNET/UnrealBuildTool.exe UE4Game Linux Development"
```

Anyway I have a workaround to enable use of the UE4 Linux images running as a user other than `ue4`, but I figured this since Jenkins builds are probably a fairly common workload this may be useful to incorporate back into `ue4-docker`. What do you reckon?

**Comment by adamrehn** [comment]
I've done some investigation, here are my initial findings:

- Adding a call to UnrealBuildTool at the end of the [ue4-minimal](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-minimal) Dockerfile does indeed allow users other than `ue4` to compile code when using Unreal Engine 4.26, but only when the user has been created properly inside the container image or the `HOME` environment variable has been set to a non-empty value to prevent UnrealBuildTool from attempting to create an XML configuration file in `/.config` (the fallback location used in place of the user's home directory.)

- This fix does not function for Unreal Engine 4.25 or older. In 4.26, `Build.sh` will attempt to rebuild UnrealBuildTool [if the Engine installation is not an Installed Build](https://github.com/EpicGames/UnrealEngine/blob/4.26.1-release/Engine/Build/BatchFiles/Linux/Build.sh#L12-L18), but under 4.25 and older [this step is unconditional](https://github.com/EpicGames/UnrealEngine/blob/4.25.4-release/Engine/Build/BatchFiles/Linux/Build.sh#L12-L16) and will fail when presented with a read-only filesystem.

- Even though project code can be compiled, cooking assets fails with an unknown cook error [`AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)`] and the log file path printed by the UAT output does not exist.

I'll need to investigate further to determine if it's possible to get cooking working. If not, then the fix will do little to help users package Unreal projects.

**Comment by slonopotamus** [comment]
Hmm... I'm successfully using `ue4-minimal` to cook packages on GitLab CI.

**Comment by RoryDungan** [comment]
Hey, thanks for looking into this! I probably should have specified, there were a few additional steps I took to get the builds working on Jenkins. 
 - First I ran `export HOME=/var/jenkins/workspace/dev_game_test@tmp` in order to get a writable home directory, since the `/var/jenkins/workspace/$PROJECT_NAME@tmp` is always guarenteed to be writable. If you wanted to test this outside of Jenkins, you could run the container with `-u $(id -u):$(id -g) -v $HOME/some-dir:/var/jenkins/workspace/test`
 - I also ran `mkdir $HOME/Saved` and `export uebp_EngineSavedFolder=$HOME/Saved` so that UE4 knows to put its saved files in there instead of under `/home/ue4/UnrealEngine`. 
 - Finally, I ran `export UE4CLI_CONFIG_DIR=/home/ue4/.config/ue4cli` so that ue4cli knows where to find its config file and in turn, where to find UE4.

I didn't list these steps initially just because it's usually reasonable to assume `$HOME` is writable even if the installation dir of the program you're running isn't. The workarounds also didn't require a new container image to be built so it wouldn't make sense to try to integrate them here.

Regarding versions lower than 4.26, I haven't tested on 4.25 but I have got this working for 4.24 and there were two extra steps that needed to be added to the Dockerfile.

First off, there is [a bug in that engine's version of RunUAT.sh](https://github.com/EpicGames/UnrealEngine/blob/4.24/Engine/Build/BatchFiles/RunUAT.sh#L54) (just a simple forward-slash in a path that ought to be a slash) that needs to be patched. This was fixed in 4.25. Secondly, I found I needed to run `FindPlatformExtensionSources.sh` in order to generate `Intermediate/ProjectFiles/UnrealBuildTool.csproj.References`. This script also doesn't exist in later versions of the engine.

Here's my Dockerfile for UE4.24:
```
FROM ue4-docker.artifactory.bigworldtech.com/ue4-full:4.24.3-opengl
RUN sed -i 's#Build\\InstalledBuild.txt#Build/InstalledBuild.txt#g' /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh
RUN /home/ue4/UnrealEngine/Engine/Build/BatchFiles/FindPlatformExtensionSources.sh
RUN bash -c "source /home/ue4/UnrealEngine/Engine/Build/BatchFiles/Linux/SetupMono.sh /home/ue4/UnrealEngine/Engine/Build/BatchFiles/Linux && \
	mono Engine/Binaries/DotNET/UnrealBuildTool.exe UE4Game Linux Development
```

**Comment by adamrehn** [comment]
@RoryDungan thanks for the additional information, it was UAT's attempts to create log files in `Engine/Programs/AutomationTool/Saved` that were causing the cook step to fail. Setting the `uebp_EngineSavedFolder` environment variable to an alternative path works around this as you've noted, as does making the default directory world-writable.

**Comment by TBBle** [comment]
I'm wondering if this would make sense to do for Windows too? Not for the user permissions (everything in WCOW is ContainerUser or ContainerAdministrator, and AFAIK [gMSA](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-run-container) is only for network identity), but if there's a first-time setup/build step we can push to container-build instead of container-run, that'd be a CI win.

**Comment by adamrehn** [comment]
@TBBle my understanding is that most of the first-time setup is related to configuring Mono, which is absent under Windows.
