### ISSUE TITLE
Have the UE4 user on Linux use a different uid.

### ISSUE THREAD

**Issue by Clockwork-Muse** [adamrehn/ue4-docker#15]
(On Linux for this, not sure what Windows is doing or how that would change this)
Switch the UE4 user to a different uid, or provide a method to remap the user.

Currently the UE4 user is being set to uid 1000 in build-prerequisites.  Unfortunately, this interferes with some schemes to mount host volumes and have permissions be set to the host user (who, on single-user desktops, will default to 1000), and interact with the editor/engine in the container.

**Comment by Clockwork-Muse** [comment]
Hrm.

The problem, really, is that we're trying to duplicate the host user into the container, including the host user's home directory (which of course won't match the path for the ue4 user).  There might be a better way to do this...

**Comment by adamrehn** [comment]
Interesting. What sort of workflow are you aiming to achieve? If the application(s) interacting with the Editor only need to invoke it as a child process and communicate via command-line arguments and standard streams (or TCP/UDP sockets), then it might be possible to create a separate container that bind-mounts the Docker socket from the host and uses `docker run` and `docker exec` to communicate with a UE4 container.

If you wanted to make that even more transparent, you could write thin wrapper scripts that use [docker-script](https://github.com/adamrehn/docker-script) to hide the Docker-related details. (After having used the [Docker Python API](https://docker-py.readthedocs.io/en/stable/) for a lot of the functionality in ue4-docker I'm actually contemplating a full Python rewrite of docker-script to significantly enhance its functionality and ease-of-use, so don't let the somewhat neglected state of the current implementation put you off.)

**Comment by Clockwork-Muse** [comment]
Actually, my primary usecase at the moment is trying to interactively use the editor.  I'm writing a plugin using OpenCV and can get it to build inside the container, but since that package doesn't get exported from the container with all the other conan packages, it makes REPL a bit awkward.

**Comment by adamrehn** [comment]
If you're using the Editor interactively then you'll have a far easier time simply [exporting the Installed Build to the host system](https://adamrehn.com/docs/ue4-docker/use-cases/linux-installed-builds) and running it on the host. If you also [export the conan-ue4cli wrapper packages to the host system](https://adamrehn.com/docs/ue4-docker/commands/export#exporting-conan-packages) and run `ue4 conan generate --profile-only` to create the Conan profile with which to use them then you should be able to build any of your own packages on the host in the same manner that you build them within a container.

I'm not entirely sure how to interpret the statement *"that package doesn't get exported from the container with all the other conan packages"*. There is no OpenCV wrapper package generated by conan-ue4cli, so presumably you're building your own package in the same manner as the [ue4-opencv-demo](https://github.com/adamrehn/ue4-opencv-demo) repository, which can be built quite happily on the host system so long as the packages on which it depends are present (which will be the case after running `ue4-docker export packages <TAG> cache` and `ue4 conan generate --profile-only`.)

**Comment by Clockwork-Muse** [comment]
:beat:
I could have _sworn_ I did that, and OpenCV was failing to build.

Only now I can get it to work, so I'm not quite sure what I was doing wrong.

Closing, as I don't need to actually to run the editor from inside the container, if I can get the extracted build to work.

Thanks!

**Comment by adamrehn** [comment]
If you were previously using an earlier version of ue4-docker and updated it in the intervening time then the build failures may have been my fault, since I was mistakenly exporting package recipes without the accompanying binaries prior to commit 6e72d3f. (Everything appeared to export correctly, but packages that depended on the wrappers would fail to build on the host due to the missing binaries.)

I'm glad to hear everything is working correctly now. Writing proper documentation for conan-ue4cli is one of the items on my TODO list for the immediate future, and this export workflow for development on the host system is actually one of the key things I want to document for users, since (as you pointed out previously) it's far more convenient than developing inside a container when you're experimenting with things.
