### ISSUE TITLE
Freezes frequently on specific step when building a plugin

### ISSUE THREAD

**Issue by alexgeek** [adamrehn/ue4-docker#158]
Output of the `ue4-docker info` command:

```
ue4-docker info
ue4-docker version:         0.0.81 (latest available version is 0.0.82)
Operating system:           Windows 10 Pro Version 2009 (OS Build 19041.928)
Docker daemon version:      20.10.5
NVIDIA Docker supported:    No
Maximum image size:         500GB
Available disk space:       320.85 GiB
Total system memory:        63.91 GiB physical, 73.41 GiB virtual
Number of processors:       12 physical, 24 logical
```

Additional details:

- Are you accessing the network through a proxy server? **Yes/No** No

Hi there, I'm building a plugin in a gitlab runner using the following command:

```
docker run --rm -v ${pwd}:c:\Workspace -w C:\Workspace adamrehn/ue4-full:4.24.3 ue4 uat BuildPlugin -VS2019 -Plugin=C:\Workspace\Plugins\LIV\LIV.uplugin -Package=C:\Workspace\PackagedPlugins\LIV -CreateSubFolder
```

This works usually (albeit very slow) but it seems to often get stuck at this point ([13/17]) and then the job times out:

```
[13/17] UE4Editor-LIV.lib
       Creating library C:\workspace\PackagedPlugins\LIV\HostProject\Plugins\LIV\Intermediate\Build\Win64\UE4Editor\Development\LIV\UE4Editor-LIV.lib and object C:\workspace\PackagedPlugins\LIV\HostProject\Plugins\LIV\Intermediate\Build\Win64\UE4Editor\Development\LIV\UE4Editor-LIV.exp
```

In Docker Desktop the it's using only 0.01% CPU, 1 GB, 49.9 GB / 13.9 GB desk read/write.

Any idea the cause?

**Comment by slonopotamus** [comment]
I very much recommend to use `--isolation=process` Docker flag. Otherwise, container only gets two cores and pretty low amount of RAM.

**Comment by alexgeek** [comment]
> I very much recommend to use `--isolation=process` Docker flag. Otherwise, container only gets two cores and pretty low amount of RAM.

Will try now, thanks

**Comment by alexgeek** [comment]
> I very much recommend to use `--isolation=process` Docker flag. Otherwise, container only gets two cores and pretty low amount of RAM.

Went from 1 hour to 2 minutes... thanks! ha
