### ISSUE TITLE
Becoming a maintainer

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#159]
Hi, @adamrehn!

It looks like you're heavily busy with other projects and don't have much time for ue4-docker. As you can see, I have already submitted a bunch of PRs that improve various aspects of ue4-docker and would like to move ue4-docker forward.

My background: 15+ years of programming, dosens of known languages (Java, C++, Python, Kotlin, Ruby, Go and so on). I am a maintainer of several FOSS projects: [asciidoctor-epub3](https://github.com/asciidoctor/asciidoctor-epub3), [git-as-svn](https://github.com/bozaro/git-as-svn), [pygments.rb](https://github.com/pygments/pygments.rb) and contributor to even more, see GitHub profile.

So, I offer my help with ue4-docker development.

Nearest goals I would like to achieve:
1. Merge current incoming PRs
2. Cleanup issues backlog
3. Introduce some form of CI. We most likely not be able to test all supported configurations (this requires too much hardware in order to run in adequate time), but something can definitely be done on this side.
4. Introduce code linter/formatter

**Comment by adamrehn** [comment]
@slonopotamus thanks so much for your generous offer of help! Balancing my time between maintaining foundational projects like ue4-docker and undertaking new work to advance the state of the Unreal Engine as a cloud native technology is becoming more and more difficult as time goes by, so additional maintainers would be wonderful. Could you please send me an email so we can schedule a video call to chat about this further?

**Comment by slonopotamus** [comment]
marat@slonopotamus.org

**Comment by adamrehn** [comment]
@slonopotamus I've now added you as a collaborator on the repository. Could you please join the Unreal Containers Community Discord server for development and maintenance discussions: https://discord.gg/x9XpGKfE
