### ISSUE TITLE
Add support for Windows 10 21H1

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#164]
Subj, it is already available for download.

**Comment by slonopotamus** [comment]
It isn't clear what Windows Server Core image is supposed to be used for 21H1. See https://github.com/microsoft/Windows-Containers/issues/117.

**Comment by slonopotamus** [comment]
21H1 won't get a matching Windows Server Core ever, see https://github.com/microsoft/Windows-Containers/issues/117. So, the best strategy is to avoid updating your host system to it and stay on 20H2 (or LTSC 2019). Closing and hoping that this messy situation will be fixed in Windows 11.

**Comment by adamrehn** [comment]
I've updated the warnings on the Unreal Containers community hub to reflect this: https://unrealcontainers.com/docs/environments/local-windows-10#optimal-performance-warning-for-windows-containers
