### ISSUE TITLE
ue4-docker export should be able to extract installed engine from ue4-minimal

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#169]
Currently, ue4-docker export only operates on ue4-full image. However, user may want to skip ue4-full image and only work with ue4-minimal images. The latter also contains fully-usable installed UE4, so can be used as a valid source for extraction.

**Comment by adamrehn** [comment]
Fixed! I'm honestly not sure why I limited it to the ue4-full image in the first place, since it's trivial to parse the version JSON file rather than using ue4cli to query the engine version.

**Comment by adamrehn** [comment]
Docs are updated: https://docs.adamrehn.com/ue4-docker/commands/export#exporting-installed-builds-under-linux
