### ISSUE TITLE
Add support for UE5

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#171]
Subj. Even though it is early alpha, many people might want to try it out. I'm not sure yet what things will need to be fixed.

**Comment by slonopotamus** [comment]
Blocked by #172

**Comment by slonopotamus** [comment]
On Linux, things might Just Work by using `ue4-docker build custom:5.0.0-early-access-1 -repo https://github.com/EpicGames/UnrealEngine/ -branch 5.0.0-early-access-1`.

**Comment by slonopotamus** [comment]
Given that #172 was merged, things might Just Work by using `ue4-docker build custom:5.0.0-early-access-1 -repo https://github.com/EpicGames/UnrealEngine/ -branch 5.0.0-early-access-1 --visual-studio 2019` on Windows.

**Comment by slonopotamus** [comment]
Nope, Windows cannot resolve .NET Core libraries when building UBT. Retrying with addition of `Nicrosoft.NetCore.Component.Runtime.3.1` to VS Build Tools.

![image](https://user-images.githubusercontent.com/92637/120333594-855bdc80-c2f8-11eb-9d3c-ed999d911970.png)

**Comment by slonopotamus** [comment]
Another obstacle: https://github.com/EpicGames/UnrealEngine/blob/5.0.0-early-access-1/Engine/Build/BatchFiles/GetDotnetPath.bat *always* uses bundled .NET Core SDK even though its comments say otherwise.

Interestingly, that file is *not* present in UE5 from Launcher.

**Comment by slonopotamus** [comment]
Trying to set UE_USE_SYSTEM_DOTNET=1 in env variables...

**Comment by slonopotamus** [comment]
One more observation: I'm not seeing this error on 20H2 host, but see in ltsc2019 Docker.

**Comment by slonopotamus** [comment]
This *might* be https://github.com/dotnet/sdk/issues/12260

**Comment by slonopotamus** [comment]
Bingo! For some reason, ue4-build-prerequisites has:

```
>docker run --rm --isolation=process adamrehn/ue4-build-prerequisites:ltsc2019-vs2019 cmd /c type C:\Users\ContainerAdministrator\AppData\Roaming\NuGet\NuGet.Config
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration />
```

I have absolutely no idea who and why creates it, so just going to remove it at the end of `install-prerequisites.bat`.

**Comment by slonopotamus** [comment]
Note: 800GB disk with only Windows + Docker + Git + Python is too small for UE5 (though it is enough for all versions of UE4.26).

**Comment by slonopotamus** [comment]
Okay, ue4-minimal almost builds on Linux:

```
Step 32/35 : RUN ./Engine/Build/BatchFiles/Linux/Build.sh UE4Editor Linux Development -NoUBTMakefiles -SkipBuild &&     mkdir -p ./Engine/Programs/AutomationTool/Saved &&      chmod a+rw ./Engine/Programs/AutomationTool/Saved && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in 0ad8938c2410
Engine/Build/BatchFiles/Linux/SetupEnvironment.sh: line 28: Engine/Build/BatchFiles/Linux/SetupDotnet.sh: No such file or directory
The command '/bin/sh -c ./Engine/Build/BatchFiles/Linux/Build.sh UE4Editor Linux Development -NoUBTMakefiles -SkipBuild &&      mkdir -p ./Engine/Programs/AutomationTool/Saved &&      chmod a+rw ./Engine/Programs/AutomationTool/Saved && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-minimal:5.0.0-early-access-1-opengl".
```

1. We need to use something different instead of `UE4Editor`. I'm going to change it to ShaderCompileWorker. Also note that the reason why this line exists at all is no longer valid since UE 4.22: https://github.com/EpicGames/UnrealEngine/commit/55cc21d08fe138fd9403d9bcca6c1092203010bf#diff-c23f687440063869ca47ea82dad1d5e3e71acac69b53de2a3b540c862fff3612L13
2. UE5 does not bundle `Engine/Build/BatchFiles/Linux/SetupDotnet.sh` (and most likely bundled .NET Core either). The same mess [happens on Windows](https://github.com/adamrehn/ue4-docker/issues/171#issuecomment-852286685) and only works because scripts do not check whether `Engine/Build/BatchFiles/GetDotnetPath.bat` succeeds. We have two options here:
2.1. Erase calls to `Engine/Build/BatchFiles/Linux/SetupDotnet.sh` + bundle .NET Core in ue4-build-prerequisites
2.2. Put a dummy script in place of `Engine/Build/BatchFiles/Linux/SetupDotnet.sh` + bundle .NET Core in ue4-build-prerequisites
2.3. Adjust `Engine/Build/InstalledEngineBuild.xml` so it bundles `Engine/Build/BatchFiles/Linux/SetupDotnet.sh` together with bundled .NET Core (`Engine/Binaries/ThirdParty/DotNet`).
2.4. Report this situation to Epics and see what they do.

**Comment by slonopotamus** [comment]
Created an issue on UDN about `SetupDotnet.sh`: https://udn.unrealengine.com/s/question/0D54z00006zfGTjCAM/linux-50ea-installed-build-is-missing-setupdotnetsh

**Comment by slonopotamus** [comment]
Okay, Epics added `SetupDotnet.sh` to list of files for installed build: https://github.com/EpicGames/UnrealEngine/commit/a18824057e6cd490750a10b59af29ca10b3d67d9

**Comment by slonopotamus** [comment]
I'm going to close this for now.

For Windows: 	`ue4-docker build custom:5.0.0-early-access-1 -repo https://github.com/EpicGames/UnrealEngine/ -branch 5.0.0-early-access-1 --visual-studio 2019 --exclude debug --no-engine --no-full`
For Linux: `ue4-docker build custom:5.0.0-early-access-1 -repo https://github.com/EpicGames/UnrealEngine/ -branch 5.0.0-early-access-1 --no-engine --no-full`

A better support might emerge when Epics release a less early-access UE5 releases.

**Comment by realvictorprm** [comment]
I'm very happy and thankfull to see that there is already some support for UE5 :)

Would the image created by the command you provided be enough for building ue5 game projects or does this need further work?

**Comment by slonopotamus** [comment]
This command produces fully-functional ue4-minimal image that can be used for whatever you would normally use ue4-minimal, yes.

**Comment by Prikalel** [comment]
> This command produces fully-functional ue4-minimal image that can be used for whatever you would normally use ue4-minimal, yes.

What's the difference in using `ue4-full` or `ue4-minimal`?
Let us say, in `ue4-full` I was able to just
```
  script:
    - ue4 build Development
    - ue4 run -ExecCmds="automation RunTests Now MyTestUnit; quit" -buildmachine -forcelogflush -unattended -nopause -nosplash -log -nullrhi | grep -v "empty engine version" > output.log || true
    - cat output.log | grep "Test Completed"
```
Do we have somthing like a `ue4` alias in `ue4-minimal` image?

**Comment by TBBle** [comment]
The presence of `ue4` is one of the main differences between `ue4-minimal` and `ue4-full`.

The others are the presence of the ue4-conan integration (which depends on CMake) and ue4-ci-helpers. See [Linux](https://github.com/adamrehn/ue4-docker/blob/v0.0.101/ue4docker/dockerfiles/ue4-full/linux/Dockerfile#L33-L55) and [Windows](https://github.com/adamrehn/ue4-docker/blob/v0.0.101/ue4docker/dockerfiles/ue4-full/windows/Dockerfile#L15-L50).

`ue4` isn't an alias, it's a script, see https://pypi.org/project/ue4cli/.
