### ISSUE TITLE
Instructions yield broken build

### ISSUE THREAD

**Issue by sysnet-ai** [adamrehn/ue4-docker#175]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.85 (latest available version is 0.0.85)
Operating system:           macOS 10.15.7 (Kernel Version 19.6.0)
Docker daemon version:      20.10.6
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       Unknown (typically means the Docker daemon is running in a Moby VM, e.g. Docker Desktop)
Total system memory:        16 GiB physical, 2 GiB virtual
Number of processors:       8 physical, 16 logica
```

Additional details:

- Are you accessing the network through a proxy server? **No**

Ran ue4-docker build got:
```
#17 19085.2   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <98fac219bd4e453693d76fda7bd96ab0>:0
#17 19085.2   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <98fac219bd4e453693d76fda7bd96ab0>:0
#17 19085.2 [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Disk full. Path /home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/Log.txt
```
after several hours of buildling.

I have more than 800Gb of free space on the disk so I'm well above the suggested 300Gib / 500Gib
```
Available Space: 875.36 GB (1.33 GB purgeable)
```

## Expected result:
Following instructions shouldn't yield a broken build when requisites are met. Either updated documentation is needed or there is a bug in the system making it take more than the recommended space.

**Comment by slonopotamus** [comment]
Could you please provide a fuller log and a command that you use to build UE4? It is currently not clear at what step you got that error. It could also be that "Disk full" error that you got doesn't actually indicate lack of disk space but instead is caused by lack of permissions.

**Comment by slonopotamus** [comment]
Oh, I just noticed you're running a MacOS. Please, see [Docker docs on disk utilization in Docker for Mac](https://docs.docker.com/docker-for-mac/space/). While you may have enough free space on your storage, ue4-docker might be hitting storage limit configured within Docker.

**Comment by sysnet-ai** [comment]
I'm still getting a broken build after resizing the image, but seems as a different thing. I'll be closing this one and creating a different issue.
