### ISSUE TITLE
Cryptic Error after 11 hours of building

### ISSUE THREAD

**Issue by sysnet-ai** [adamrehn/ue4-docker#176]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.85 (latest available version is 0.0.85)
Operating system:           macOS 10.15.7 (Kernel Version 19.6.0)
Docker daemon version:      20.10.6
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       Unknown (typically means the Docker daemon is running in a Moby VM, e.g. Docker Desktop)
Total system memory:        16 GiB physical, 3 GiB virtual
Number of processors:       8 physical, 16 logical
```

Additional details:

- Are you accessing the network through a proxy server? **No**

Have been trying to get UE4 docker for almost a week now. Errors are consistently cryptic. If the command takes several hours to run, a full log spitted at the end would be really useful so less guess work is required.
After several times of getting 'Full Disk' as an error, I'm now getting an error after running:
```
>>>ue4-docker build 4.26.1 --no-engine


ERRROR:
#17 39627.2   [2490/2783] Link (lld) libUE4Editor-PythonScriptPluginPreload.so
#17 39627.4   [2491/2783] Link (lld) libUE4Editor-IPC.so
#17 39627.6   [2492/2783] Copy libtbb.so.2
#17 39627.8   [2493/2783] Copy AgentInterface.dll
#17 39634.6 Took 39016.987335s to run mono, ExitCode=6
#17 39635.1 UnrealBuildTool failed. See log for more details. (/home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UE4Editor-Linux-DebugGame.txt)
#17 39635.3 AutomationTool exiting with ExitCode=6 (6)
#17 39636.2 RunUAT ERROR: AutomationTool was unable to run successfully.
------
executor failed running [/bin/sh -c ./Engine/Build/BatchFiles/RunUAT.sh BuildGraph -target="Make Installed Build Linux" -script=Engine/Build/InstalledEngineBuild.xml -set:HostPlatformOnly=true -set:WithDDC=$BUILD_DDC  && 	rm -R -f /home/ue4/UnrealEngine/LocalBuilds/InstalledDDC && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '']: exit code: 6
[ue4-docker build] Error: failed to build image "adamrehn/ue4-minimal:4.26.1-opengl".
```

Is there any way the tool could provide additional context on what is failing? "AutomationTool was unable to run successfully." provides no useful or actionable steps.
Is there a way UE4-docker get the logs and put them where we ran the command? Or display the last 100 lines in the command line? Or at the very least spit out the docker command that would get to the logs or the image name? It proves very complicated to extract the logs of an image that has already been stopped. Or at the very least can some health-check be executed at the beginning of the run (Check for enough disk, check for enough memory, check for any dependencies) so that it doesn't require 10+ hours before an error message is produced?

**Comment by slonopotamus** [comment]
Closing, given that @sysnet-ai managed to build UE4: https://discord.com/channels/844118704941170688/844121757530718238/852989157235490877
