### ISSUE TITLE
Migrate away from travis-ci.org

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#178]
Subj. travis-ci.org is dead:

https://travis-ci.org/github/adamrehn/ue4-docker

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

This effectively means that we currently don't have automated release publishing to PyPI.

**Comment by TBBle** [comment]
https://blog.travis-ci.com/2021-05-07-orgshutdown

> This means that any repositories you currently have connected to travis-ci.org must be migrated over to travis-ci.com before the end of May 2021 if you want your builds to continue without interruption. To do this you can simply sign up to travis-ci.com and link the repositories that you want to migrate. Your existing configurations will work as expected on travis-ci.com and you do not need to alter your build definitions. Alternatively, there’s a migration feature, which will allow transferring a limited amount of build history data from travis-ci.org to travis-ci.com.

I guess @adamrehn would have to sign up for travis-ci.com as the account holder and activate the builds there?

**Comment by jonpas** [comment]
Correct, that's how it worked before it fully shut down at least. Just login to the .com page, press activate and that should be it.

**Comment by slonopotamus** [comment]
Aaaand... looks like it works: https://github.com/adamrehn/ue4-docker/runs/3122538136?check_suite_focus=true#step:7:1
