### ISSUE TITLE
Facing issue while running ue4-docker build 4.20.3

### ISSUE THREAD

**Issue by DevOps-Hestabit-1** [adamrehn/ue4-docker#181]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.86 (latest available version is 0.0.86)
Operating system:           Windows Server 2016 Datacenter Version 1607 (Build 14393.4467)
Docker daemon version:      1.12.2-cs2-ws-beta
NVIDIA Docker supported:    No
Maximum image size:         400GB
Available disk space:       479.79 GiB
Total system memory:        7.65 GiB physical, 9.53 GiB virtual
Number of processors:       2 physical, 4 logical
```

Additional details:

- Are you accessing the network through a proxy server? No

Facing issue while running ue4-docker build 4.20.3
Sending build context to Docker daemon 2.428 MB
Step 1/28 : ARG BASEIMAGE
Please provide a source image with from prior to commit
[ue4-docker build] Error: failed to build image "adamrehn/ue4-build-prerequisites:ltsc2016-vs2017".

**Comment by slonopotamus** [comment]
> Docker daemon version:      1.12.2-cs2-ws-beta

Your Docker version is catastrophically old. Please, upgrade to something from 2021 (or at least from 2020.

**Comment by slonopotamus** [comment]
To be more exact, we need Docker >= 17.05 because of this feature: https://github.com/moby/moby/pull/31352

**Comment by DevOps-Hestabit-1** [comment]
Thank you Mate this fixed the issue.
