### ISSUE TITLE
Add Ubuntu 20.04 as base image

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#183]
Subj

**Comment by slonopotamus** [comment]
Ideally, we should allow to pass a whatever image user wants as a base image. Current `cudagl` tags that ue4-docker supports are already two year old ([10.2](https://github.com/adamrehn/ue4-docker/blob/v0.0.87/ue4docker/infrastructure/BuildConfiguration.py#L17-L20)) while latest available is 11.4.0. It isn't worth following  their release pace.

**Comment by adamrehn** [comment]
I agree that users should have the flexibility to pass arbitrary base images, although they'd need to be based on Debian/Ubuntu for our `apt` commands to work correctly and we'd probably also want to make it clear that we can't help people with troubleshooting issues that occur when using base images that the maintainers don't test against.
