### ISSUE TITLE
Split debug symbols into a separate filesystem layer

### ISSUE THREAD

**Issue by adamrehn** [adamrehn/ue4-docker#184]
So in the lead up to the release of Unreal Engine 4.27 and the impending [availability of prebuilt container images for all licensees](https://portal.productboard.com/epicgames/1-unreal-engine-public-roadmap/c/320-ue-container-build-beta), I've been thinking about the experience for developers who are pulling these images and what will happen when they pull different image variants. As can be seen in the [generation script](https://github.com/EpicGames/UnrealEngine/blob/4.27/Engine/Extras/Containers/Dockerfiles/linux/generate.sh) and [build script](https://github.com/EpicGames/UnrealEngine/blob/4.27/Engine/Extras/Containers/Dockerfiles/linux/build.sh) for the official images, there will be two development images available which are based on [ue4-minimal](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-minimal):

- `ghcr.io/epicgames/unreal-engine:dev-4.27.0`, which **includes** debug symbols and templates
- `ghcr.io/epicgames/unreal-engine:dev-slim-4.27.0`, which **excludes** debug symbols and templates

As the Dockerfile currently stands, the majority of the data in the largest filesystem layer (the one including the Installed Build of the Engine) is going to be duplicated when pulling the two image variants, since the [removal of debug symbols](https://github.com/adamrehn/ue4-docker/blob/v0.0.87/ue4docker/dockerfiles/ue4-minimal/linux/Dockerfile#L43-L47) takes place prior to [copying the Installed Build into a new build stage](https://github.com/adamrehn/ue4-docker/blob/v0.0.87/ue4docker/dockerfiles/ue4-minimal/linux/Dockerfile#L74-L75), leaving the version of the `COPY` layer with debug symbols included completely unrelated to the version without debug symbols. This isn't ideal, since users who want both image variants will be pulling the same data twice.

The ideal situation is one where the debug symbols are in a separate layer that stacks on top of the Installed Build, ensuring any given file is only pulled once. This should be feasible if we move the files to a separate directory rather than deleting them, and then merge them in using a second `COPY` directive in the subsequent build stage. Unfortunately, we can't just perform a straight merge this way, as evidenced when testing a simple example Dockerfile:

```dockerfile
# Create some files and directories
FROM ubuntu:20.04 as first
RUN mkdir /root
RUN mkdir /root/a && mkdir /root/b && mkdir /root/a/c
RUN echo '1' > /root/a/1.txt
RUN echo '2' > /root/b/2.txt
RUN echo '3' > /root/a/c/3.txt

# Create additional files and directories under the same parent directory
FROM ubuntu:20.04 as second
RUN mkdir /root
RUN mkdir /root/d && mkdir mkdir /root/a/e
RUN echo '4' > /root/d/4.txt
RUN echo '5' > /root/a/e/5.txt

# Copy the first set of files and directories
FROM ubuntu:20.04 as final
COPY --from=first /root /root

# Attempt to merge the second set of files and directories with the first
# (These directives both fail with the error `mkdir: cannot create directory '/root': File exists`)
COPY --from=second /root /root
COPY --from=second /root/**/*.txt /root
```

I can think of two potential approaches to work around this limitation:

- Copy the files to a separate parent directory in the `COPY` directive and then hardlink or symlink them into the correct locations using a `RUN` directive, since performing a move operation here will duplicate the file data in the new filesystem layer. (OCI container image filesystem layers have no concept of renaming a file or directory, just [adding, modifying and removing](https://github.com/opencontainers/image-spec/blob/main/layer.md#change-types).) This approach should be compatible across both Linux and Windows containers.

- Use the [--mount=type=bind](https://github.com/moby/buildkit/blob/v0.9.0/frontend/dockerfile/docs/syntax.md#run---mounttypebind-the-default-mount-type) feature from BuildKit to mount the separate parent directory from the previous build stage and then copy the files into place. This approach is far cleaner, but is only compatible with Linux containers until the efforts to add Windows container support to BuildKit are complete.

It is worth noting that this improvement will do nothing to address the frustrations related to Windows filesystem size limit bugs, since the debug symbols will still be committed in the same filesystem layer as the Installed Build of the Engine in the build stage that creates them, and the split layers only exist in the final image.

@slonopotamus @TBBle what are your thoughts on the best way to approach this? Is there value in using the same approach across Linux and Windows for the sake of consistency, or should we use what works best for each platform? Are there any alternative approaches that I've overlooked?

**Comment by TBBle** [comment]
My initial thought is that
```
COPY --from=second /root /root
```
should have worked, [the `COPY` docs](https://docs.docker.com/engine/reference/builder/#copy) explicitly allow for the destination already existing, and we're looking at a core use-case for `COPY --from`.

Perhaps try
```
COPY --from=second /root/ /root/
```
in case the lack of trailing slash is (somewhat user-hostilely) distinguishing "copy into this directory" from "make that a copy of this".

A quick poke at the Moby issue tracker doesn't show this particular problem, but it does show that `COPY` has had (and still has) some weird and surprising behaviours over the years. Apparently BuildKit does something different again internally too.

**Comment by slonopotamus** [comment]
@adamrehn There were several bugs in your Dockerfile.

Initially, it fails at `RUN mkdir /root` because `/root` dir already exists. Then, there are a bit more places where dir either exists or you're trying to create deep directory hierarchy by `mkdir` without `-p`.

After fixing those (mainly, by adding `-p` here and there), this is what I ended up with:

```Dockerfile
# Create some files and directories
FROM ubuntu:20.04 as first
RUN mkdir -p /root
RUN mkdir /root/a && mkdir /root/b && mkdir /root/a/c
RUN echo '1' > /root/a/1.txt
RUN echo '2' > /root/b/2.txt
RUN echo '3' > /root/a/c/3.txt

# Create additional files and directories under the same parent directory
FROM ubuntu:20.04 as second
RUN mkdir -p /root
RUN mkdir /root/d && mkdir -p /root/a/e
RUN echo '4' > /root/d/4.txt
RUN echo '5' > /root/a/e/5.txt

# Copy the first set of files and directories
FROM ubuntu:20.04 as final
COPY --from=first /root /root

# Attempt to merge the second set of files and directories with the first
# (These directives both fail with the error `mkdir: cannot create directory '/root': File exists`)
COPY --from=second /root /root
COPY --from=second /root/**/*.txt /root
```

And this thing does build successfully.

**Comment by adamrehn** [comment]
Oh my goodness, I misinterpreted which directive was generating the error. Evidently this is what happens if I write and debug code when I have a head cold. 🤦

Thanks for spotting that @slonopotamus. I'll return to this and run an equivalent Windows test once my germ-addled brain has recovered.

**Comment by adamrehn** [comment]
Initial implementation is in commit 4e6e64b, currently testing to ensure I haven't inadvertently broken anything.

**Comment by slonopotamus** [comment]
I like what you [did](https://github.com/adamrehn/ue4-docker/commit/4e6e64bf69de18c9b7916351e4ec132551bd98db#diff-2faa50ca4c6d80d7dd0e093c700a90935e359adf3b9ea640a108c2b8d1cbd9edR258) to `-set:VS2019=true`. Didn't think about doing that on Jinja level.

**Comment by slonopotamus** [comment]
BTW. Maybe we now can build with debug info on Windows without hitting 20GB bug given that PDBs are copied in a separate step from the rest of the engine?!

**Comment by TBBle** [comment]
My recollection from that issue is that the PDBs alone are still > 20GB, but I haven't checked that myself.

**Comment by adamrehn** [comment]
As I noted in my initial comment, the debug symbols are still committed in the same filesystem layer as the Installed Build itself when they're created, it's only afterwards that we split them out, so sadly I think we'll still be bottlenecked by those bugs on the original filesystem layer before we ever get to the point where we split them out.

**Comment by slonopotamus** [comment]
> PDBs alone are still > 20GB

Whoops.

> I think we'll still be bottlenecked by those bugs on the original filesystem layer before we ever get to the point where we split them out.

The only bug that is still not fixed in any released docker version happens during `COPY` of more than 20GB.

**Comment by slonopotamus** [comment]
> PDBs alone are still > 20GB

You're right, they're almost 40GB for 5.0EA2.

**Comment by slonopotamus** [comment]
So, I guess this issue can be closed? I ran some tests and everything seems to work fine. @adamrehn?

**Comment by adamrehn** [comment]
I still haven't been able to test under Windows due to a rather frustrating sequence of events:

- My 20H2 installation decided to stop booting and I had to do a fresh install.
- After the fresh install, Docker Desktop started misbehaving. It would work fine upon initial installation, but after a reboot it would fail to start either the Windows containers backend or Linux containers backend. A fresh install of Windows and Docker Desktop would fix it, but only until the first reboot.
- Just this evening, I finally managed to get Docker working by downloading the Docker EE binaries designed for Windows Server and manually running `dockerd`.

@slonopotamus are you satisfied with your testing under Windows using UE5, or would you like me to test 4.26 or 4.27 as well?

**Comment by slonopotamus** [comment]
@adamrehn well, due to 20GB bug, we currently only can build without PDBs on Windows (and I tried that successfully). I think this PR is independent of engine version, so we don't need to do full testing.

So, it can be closed.

**Comment by slonopotamus** [comment]
> After the fresh install, Docker Desktop started misbehaving. It would work fine upon initial installation, but after a reboot it would fail to start either the Windows containers backend or Linux containers backend.

I got the same issue. I suspect that Docker Desktop 3.6.0 is SNAFU: https://github.com/docker/for-win/issues/11934#issuecomment-901668502
