### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by alexgeek** [adamrehn/ue4-docker#197]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.89 (latest available version is 0.0.89)
Operating system:           Windows 10 Pro (Build 19042.1110)
Docker daemon version:      20.10.8
NVIDIA Docker supported:    No
Maximum image size:         500GB
Available disk space:       883.08 GiB
Total system memory:        63.91 GiB physical, 75.41 GiB virtual
Number of processors:       12 physical, 24 logical
```

Additional details:

- Are you accessing the network through a proxy server? **Yes/No**
- No

Hi I get the following trying to build UE4.27:
```
Cloning into 'C:\UnrealEngine'...
remote: Repository not found.
fatal: repository 'https://github.com/EpicGames/UnrealEngine.git/' not found
```

Using:

```
ue4-docker build 4.27.0 --no-engine --exclude ddc --exclude templates -username alexgeek -password [personal access token]
```

To be clear I definitely have access to the UE4 repositories.

**Comment by slonopotamus** [comment]
Did you add `repo` scope to Github access token?

**Comment by alexgeek** [comment]
> Did you add `repo` scope to Github access token?

Ah thank you it works now. I tried to use a subset of the repo scopes as I didn't think it needed "full control".
