### ISSUE TITLE
Support execution of ue4docker module with `-m`

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4-docker#20]
Currently, the only ways to run ue4docker are either the generated `ue4-docker.exe`, or
```powershell
py -c 'from ue4docker import main; main()' info
```

`ue4-docker.exe` requires that `Scripts` either be in the `PATH`, or be in a known directory.

As my host use-case requires multiple versions of Python installed on Windows, I generally don't have any Python in the path, but rely on `py` from the Python Launcher for Windows, and/or virtualenvs to setup path for specific packages.

It would be nice if `py -m ue4docker info` worked, similarly to how `py -m pip install` works, when working with a system install of ue4docker, e.g. on a (dedicated) image for executing ue4docker, which is what I'm currently working on.

This is as simple as creating a new file `__main__.py` next to `__init__.py`:
```py
if __name__ == "__main__":
        from .main import main
        main()
```
as the `-m` command works by looking for a module named `__main__` in the supplied package, and executing it.

I tested this by adding the `__main__.py` to a copy installed in a temporary virtualenv on Python 3.7 on my Windows desktop.

**Comment by adamrehn** [comment]
Thanks for the feature suggestion! This is now implemented in ue4-docker version 0.0.26.
