### ISSUE TITLE
Stop using/installing curl in Windows images

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#218]
Subj. I don't know any reason why we can't just use PowerShell to download files.

The only thing that might become a show-stopper is [git-credential-helper.bat](https://github.com/adamrehn/ue4-docker/blob/master/ue4docker/dockerfiles/ue4-source/windows/git-credential-helper.bat). I dunno whether PowerShell has that functionality.

**Comment by slonopotamus** [comment]
BTW, [Windows has curl preinstalled](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows). And if I'm not mistaken, that covers all our supported versions (2019 LTSC is the oldest).

**Comment by TBBle** [comment]
If the built-in curl in Windows works, then great. I recall it wasn't present on LTSC 2016, and I have had experience that some things are not available without a newer build of curl; but I doubt they affect us.
