### ISSUE TITLE
maxsize diagnostics fails on Windows Server 2022

### ISSUE THREAD

**Issue by jonpas** [adamrehn/ue4-docker#263]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.98 (latest available version is 0.0.98)
Operating system:           Windows Server 2022 Datacenter (Build 20348.709)
Docker daemon version:      20.10.16.1
NVIDIA Docker supported:    No
Maximum image size:         400GB
Available disk space:       618.44 GiB
Total system memory:        15.65 GiB physical, 2.88 GiB virtual
CPU:                        2 physical, 4 logical (AMD64 Family 25 Model 1 Stepping 1, AuthenticAMD)
```
(Actual ue4-docker version is of this commit: f6b30c7c1cc55c747241eb3ffb64fc802139f5a6)

Additional details:

- Are you accessing the network through a proxy server? **No**

Running `ue4-docker diagnostics all` will fail on `maxsize` diagnostics with the following error message:
```
[ue4-docker diagnostics] [maxsize] Run: ['docker', 'run', '--rm', '--storage-opt', 'size=200GB', 'mcr.microsoft.com/windows/nanoserver:1903', 'cmd', 'exit']
Unable to find image 'mcr.microsoft.com/windows/nanoserver:1903' locally
1903: Pulling from windows/nanoserver
302b7cf33b3a: Pull complete
Digest: sha256:6f95750a59a675c734e6772e8cd98d2b6851e03e828e80ca34817756b7c16c82
Status: Downloaded newer image for mcr.microsoft.com/windows/nanoserver:1903
docker: Error response from daemon: hcsshim::CreateComputeSystem 7963149c3ac6afad00ae6004ee8a82f22ac3215695ec8ca73d25221ed13fd7d1: The container operating system does not match the host operating system.

[ue4-docker diagnostics] [maxsize] Diagnostic failed! The host platform cannot specify maximum image sizes using Docker's `storage-opt` configuration key.
```

I assume the error is caused due to `nanoserver:1903`, which is not "compatible" with Windows Server 2022.

**Comment by slonopotamus** [comment]
It's tempting to just remove this diagnostic. We have code (https://github.com/adamrehn/ue4-docker/blob/v0.0.98/ue4docker/infrastructure/WindowsUtils.py#L92-L103) that will print an error if user tries to run ue4-docker on systems that are affected by that issue. And 1903 is EOL anyway.

**Comment by TBBle** [comment]
Yeah, it's bitrotted. I think versions of Docker before the workaround in 19.03.6 are probably well-and-truely EOL too. This is the only diagnostic which is using a stock image, the others all build a servercore-based image as part of the diagnostic.

I agree it's not worth fixing this, this many years later, the problem's not coming back in a new Windows release. A fallback would be to limit the maximum version of the diagnostic, since right now we limit the minimum version (which is how this didn't show up on Server 2019 for example).
