### ISSUE TITLE
Cuda Version 10.1 released

### ISSUE THREAD

**Issue by Clockwork-Muse** [adamrehn/ue4-docker#27]
Cuda Version 10.1 was released in February 2019, but attempting to specify it as a build parameter (`ue4-docker build 4.22.0 --linux --cuda=10.1`) fails with:

```
[ue4-docker build] Error: unsupported CUDA version "10.1", supported versions are: 9.2, 10.0
```

**Comment by adamrehn** [comment]
Sorry about that oversight, I've added 10.1 to the supported list. I'm planning on incorporating the tag listing functionality from the [ue4-runtime build script](https://github.com/adamrehn/ue4-runtime/blob/master/build.py) into ue4-docker in the very near future, which will allow it to auto-detect the supported tags without needing to rely on a hardcoded list.
