### ISSUE TITLE
Do the project consider to support ue5 docker build images and runtime?

### ISSUE THREAD

**Issue by andyzheung** [adamrehn/ue4-docker#270]
As the titile says.

**Comment by slonopotamus** [comment]
We have UE5 support. Just `ue4-docker build 5.0.3-release --target=minimal` and you'll get ready to use image.

More than that, Dockerfiles for official Unreal Engine images are generated using ue4-docker:
https://github.com/EpicGames/UnrealEngine/blob/5.0.3-release/Engine/Extras/Containers/Dockerfiles/linux/generate.sh#L49
