### ISSUE TITLE
Ubuntu 22.04 UE 5.1.0 build fails due to missing dependency

### ISSUE THREAD

**Issue by russkel** [adamrehn/ue4-docker#280]
```
#19 38615.1 LogCore: Warning: dlopen failed: libxkbcommon.so.0: cannot open shared object file: No such file or directory
```

https://packages.ubuntu.com/search?searchon=contents&keywords=libxkbcommon.so&mode=exactfilename&suite=jammy&arch=any

PR incoming.

**Comment by adamrehn** [comment]
@russkel this was already fixed in commit 2d0ef0d, which is included in ue4-docker version 0.0.101 and newer. You simply need to update to the latest version.

**Comment by russkel** [comment]
Thanks @adamrehn, I saw that line but thought maybe it needed `-dev`. Awesome.

**Comment by slonopotamus** [comment]
Wait, how you're building 22.04? Where you got `nvidia/opengl:1.0-glvnd-devel-22.04` base image from?

**Comment by russkel** [comment]
@slonopotamus I built it myself using the nvidia tooling (https://gitlab.com/nvidia/container-images/cuda#building-from-source) with a slight patch to the `build.sh` removing the git checkout and used the `ubuntu20.04` branch renamed to `ubuntu22.04`. Works well so far.

Ref #276
