### ISSUE TITLE
executor failed running [/bin/sh -c ue4 conan generate...]

### ISSUE THREAD

**Issue by pawelkadziela** [adamrehn/ue4-docker#289]
Output of the `ue4-docker info` command:

> I am using WSL2 with Ubuntu - 'ue4-docker info' ends with error:
> FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/docker'

Additional details:

- Are you accessing the network through a proxy server? No

Hello,
I am trying to build 5.0.3 unreal engine. Managed to create necessary images in previous steps but 'adamrehn/ue4-full' fails with following error:

> xxxxx@xxxxx:~$ ue4-docker build 5.0.3 --cuda=11.3.1
> [ue4-docker build] COMMAND-LINE INVOCATION:
> [ue4-docker build] ['ue4-docker', '5.0.3', '--cuda=11.3.1']
> 
> [ue4-docker build] UNREAL ENGINE VERSION SETTINGS:
> [ue4-docker build] Custom build:  No
> [ue4-docker build] Release:       5.0.3
> [ue4-docker build] Repository:    https://github.com/EpicGames/UnrealEngine.git
> [ue4-docker build] Branch/tag:    5.0.3-release
> 
> [ue4-docker build] ADVANCED CONFIGURATION OPTIONS:
> [ue4-docker build] excluded_components: {"ddc": false, "debug": false, "templates": false}
> 
> [ue4-docker build] LINUX CONTAINER SETTINGS
> [ue4-docker build] Base OS image: nvidia/cudagl:11.3.1-devel-ubuntu18.04
> 
> [ue4-docker build] GENERAL SETTINGS
> [ue4-docker build] Build targets: build-prerequisites full minimal source
> [ue4-docker build] Changelist override: (None specified)
> [ue4-docker build] Not excluding any Engine components.
> [ue4-docker build] Not building the ue4-source image, no Git credentials required.
> 
> [ue4-docker build] Image "adamrehn/ue4-build-prerequisites:cudagl11.3.1-ubuntu18.04" exists and rebuild not requested, skipping build.
> 
> [ue4-docker build] Image "adamrehn/ue4-source:5.0.3-cudagl11.3.1-ubuntu18.04" exists and rebuild not requested, skipping build.
> 
> [ue4-docker build] Image "adamrehn/ue4-minimal:5.0.3-cudagl11.3.1-ubuntu18.04" exists and rebuild not requested, skipping build.
> [ue4-docker build] Building image "adamrehn/ue4-full:5.0.3-cudagl11.3.1-ubuntu18.04"...
[+] Building 3.9s (12/19)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 4.07kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/adamrehn/ue4-minimal:5.0.3-cudagl11.3.1-ubuntu18.04                     0.0s
 => [internal] load metadata for docker.io/adamrehn/ue4-source:5.0.3-cudagl11.3.1-ubuntu18.04                      0.0s
 => [conan 1/5] FROM docker.io/adamrehn/ue4-source:5.0.3-cudagl11.3.1-ubuntu18.04                                  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 44B                                                                                   0.0s
 => CACHED [stage-1 1/9] FROM docker.io/adamrehn/ue4-minimal:5.0.3-cudagl11.3.1-ubuntu18.04                        0.0s
 => CACHED [conan 2/5] RUN pip3 install --upgrade pip setuptools wheel && echo '' && echo 'RUN directive complete  0.0s
 => CACHED [conan 3/5] RUN pip3 install "ue4cli>=0.0.45" "conan-ue4cli>=0.0.27" && echo '' && echo 'RUN directive  0.0s
 => CACHED [conan 4/5] RUN ue4 setroot /home/ue4/UnrealEngine && echo '' && echo 'RUN directive complete. Docker   0.0s
 => ERROR [conan 5/5] RUN ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit t  3.8s
 => CANCELED [stage-1 2/9] RUN apt-get update && apt-get install -y --no-install-recommends cmake && echo '' && e  3.8s
 > [conan 5/5] RUN ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '':
#13 3.765 Using user-specified engine root: /home/ue4/UnrealEngine
#13 3.765 Removing the "ue5.0-Linux-x86_64-unknown-linux-gnu" Conan profile if it already exists...
#13 3.765 Removing any previous versions of profile base packages...
#13 3.765 Creating "ue5.0-Linux-x86_64-unknown-linux-gnu" Conan profile using autodetected settings...
#13 3.765 Installing profile base packages...
#13 3.765 Copying the "ue5.0-Linux-x86_64-unknown-linux-gnu" Conan profile into a new profile named "ue4"...
#13 3.765 Retrieving thirdparty library list from UBT...
#13 3.766 Traceback (most recent call last):
#13 3.766   File "/usr/local/bin/ue4", line 8, in <module>
#13 3.766     sys.exit(main())
#13 3.766   File "/usr/local/lib/python3.6/dist-packages/ue4cli/cli.py", line 222, in main
#13 3.766     SUPPORTED_COMMANDS[command]['action'](manager, args)
#13 3.766   File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/main.py", line 48, in main
#13 3.766     SUBCOMMANDS[subcommand]['function'](manager, args[1:])
#13 3.766   File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/commands/generate.py", line 153, in generate
#13 3.766     libs = [lib for lib in manager.listThirdPartyLibs() if lib != 'libc++']
#13 3.766   File "/usr/local/lib/python3.6/dist-packages/ue4cli/UnrealManagerBase.py", line 183, in listThirdPartyLibs
#13 3.766     return interrogator.list(self.getPlatformIdentifier(), configuration, self._getLibraryOverrides())
#13 3.766   File "/usr/local/lib/python3.6/dist-packages/ue4cli/UE4BuildInterrogator.py", line 20, in list
#13 3.766     modules = self._getThirdPartyLibs(platformIdentifier, configuration)
#13 3.766   File "/usr/local/lib/python3.6/dist-packages/ue4cli/UE4BuildInterrogator.py", line 170, in _getThirdPartyLibs
#13 3.766     self.runUBTFunc('UnrealEditor', platformIdentifier, configuration, args)
#13 3.766   File "/usr/local/lib/python3.6/dist-packages/ue4cli/UnrealManagerBase.py", line 695, in <lambda>
#13 3.766     ubtLambda = lambda target, platform, config, args: self._runUnrealBuildTool(target, platform, config, args, True)
#13 3.766   File "/usr/local/lib/python3.6/dist-packages/ue4cli/UnrealManagerBase.py", line 687, in _runUnrealBuildTool
#13 3.766     return Utility.capture(arguments, cwd=self.getEngineRoot(), raiseOnError=True)
#13 3.766   File "/usr/local/lib/python3.6/dist-packages/ue4cli/Utility.py", line 129, in capture
#13 3.766     '\nstderr: "' + stderr + '"'
#13 3.766 Exception: child process ['/home/ue4/UnrealEngine/Engine/Build/BatchFiles/Linux/Build.sh', 'UnrealEditor', 'Linux', 'Development', '-Mode=JsonExport', '-OutputFile=/tmp/tmpo1c7c8dr/ubt_output.json'] failed with exit code 1
#13 3.766 stdout: "Setting up bundled DotNet SDK
#13 3.766 Running command : dotnet Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll UnrealEditor Linux Development -Mode=JsonExport -OutputFile=/tmp/tmpo1c7c8dr/ubt_output.json
#13 3.766
#13 3.766 Welcome to .NET Core 3.1!
#13 3.766 ---------------------
#13 3.766 SDK Version: 3.1.401
#13 3.766
#13 3.766 Telemetry
#13 3.766 ---------
#13 3.766 The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
#13 3.766
#13 3.766 Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
#13 3.766
#13 3.766 ----------------
#13 3.766 Explore documentation: https://aka.ms/dotnet-docs
#13 3.766 Report issues and find source on GitHub: https://github.com/dotnet/core
#13 3.766 Find out what's new: https://aka.ms/dotnet-whats-new
#13 3.766 Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
#13 3.766 Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
#13 3.766 Write your first app: https://aka.ms/first-net-core-app
#13 3.766 --------------------------------------------------------------------------------------
#13 3.766 "
#13 3.766 stderr: "Could not execute because the specified command or file was not found.
#13 3.766 Possible reasons for this include:
#13 3.766   * You misspelled a built-in dotnet command.
#13 3.766   * You intended to execute a .NET Core program, but dotnet-Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll does not exist.
#13 3.766   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
#13 3.766 "
executor failed running [/bin/sh -c ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '']: exit code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-full:5.0.3-cudagl11.3.1-ubuntu18.04".

I will appreciate any help as in that case I got stuck with no idea how to resolve that.

**Comment by TBBle** [comment]
Looks like the same thing as #281, see https://github.com/adamrehn/conan-ue4cli/issues/20 for where this is being looked into, as it appears to be a conan-ue4cli issue; although it's possible that fixing this will end up needing changes in the ue4-full image.

**Comment by pawelkadziela** [comment]
I am sorry for not paying attention and duplicating issues. Thank you for explanations.

**Comment by petergerten** [comment]
I tried building with a patched version of conan-ue4cli:
`ue4-docker build --cuda=11.4.2 -basetag ubuntu20.04 --ue-version 5.0.3 -conan-ue4cli git+https://github.com/JJC1138/conan-ue4cli.git@ue5fix`
and
`ue4-docker build --cuda=11.4.2 -basetag ubuntu20.04 --ue-version 5.0.3 -conan-ue4cli git+https://github.com/Greenroom-Robotics/conan-ue4cli.git@feature/fix-libcxx`

(The patched version refer to https://github.com/adamrehn/conan-ue4cli/pull/21 and https://github.com/adamrehn/conan-ue4cli/pull/15)

But unfortunately it did not make any difference. I still get the error message same as the orignal post of this thread.

(also see https://github.com/adamrehn/ue4-docker/issues/281)
