### ISSUE TITLE
Unable to build UE4 docker image

### ISSUE THREAD

**Issue by papa-singh** [adamrehn/ue4-docker#303]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.105 (latest available version is 0.0.105)
Operating system:           Linux (Ubuntu 20.04.5 LTS, 5.15.0-67-generic)
Docker daemon version:      23.0.1
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       332.37 GiB
Total system memory:        125.43 GiB physical, 30.52 GiB virtual
CPU:                        12 physical, 12 logical (x86_64)

```

Additional details:

- Are you accessing the network through a proxy server? No

I created issue #301 on Friday, last week, because I was unable to build Unreal Engine using the command `ue4-docker build 4.24.3
`. You seem to to have fixed that issue and introduced another one in the process. Now, I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/ram/.local/bin/ue4-docker", line 8, in <module>
    sys.exit(main())
  File "/home/ram/.local/lib/python3.8/site-packages/ue4docker/main.py", line 109, in main
    COMMANDS[command]["function"]()
  File "/home/ram/.local/lib/python3.8/site-packages/ue4docker/build.py", line 52, in build
    config = BuildConfiguration(parser, sys.argv[1:], logger)
  File "/home/ram/.local/lib/python3.8/site-packages/ue4docker/infrastructure/BuildConfiguration.py", line 410, in __init__
    raise Exception()
Exception
```

**Comment by slonopotamus** [comment]
Aaargh!

**Comment by papa-singh** [comment]
@slonopotamus Can you please push the changes to PyPI, thanks.

Also, I'm actually trying to build the UE editor for Carla Simulator. According the[ instructions on their page,](https://github.com/carla-simulator/carla/blob/master/Util/Docker/README.md) the command to build is `ue4-docker build 4.24.3 --no-engine --no-minimal` but when I run this I get an error saying `no-engine` is not a valid argument. Was support for this removed? What does it actually do?

**Comment by slonopotamus** [comment]
Sorry for inconvenience, looks like I undertested some of my recent refactorings. Pushed in 0.0.106.

**Comment by slonopotamus** [comment]
> Was support for this removed?

Yep, just drop it. There was `ue4-engine` image that nobody used: https://github.com/adamrehn/ue4-docker/pull/273

WRT docs - we're in the process of migrating docs to this repo (mainly because docs get outdated). You can take a look at a more-up-to-date version here: https://ue4-docker.docs.adamrehn.com/#ue4-docker-build

**Comment by papa-singh** [comment]
> > Was support for this removed?
> 
> Yep, just drop it. There was `ue4-engine` image that nobody used: #273
> 
> WRT docs - we're in the process of migrating docs to this repo (mainly because docs get outdated). You can take a look at a more-up-to-date version here: https://ue4-docker.docs.adamrehn.com/#ue4-docker-build

Thanks for the information. Will create another issue if I run into any other problem :sweat_smile:
