### ISSUE TITLE
Support for 5.1.1 on linux

### ISSUE THREAD

**Issue by keckj** [adamrehn/ue4-docker#314]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.106 (latest available version is 0.0.106)
Operating system:           Linux (Linux Mint 20.1, 5.4.0-131-generic)
Docker daemon version:      20.10.21
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       896.09 GiB
Total system memory:        754.53 GiB physical, 0 bytes virtual
CPU:                        56 physical, 56 logical (x86_64)

```

Additional details:

- Are you accessing the network through a proxy server? No

- With the same configuration (ubuntu20.04 and cuda11.8), I managed to build 4.27.2 and 5.0.3 but failed to build the image with 5.1.1

- I am not sure this is a ue4-docker problem (maybe ue4 or a DNS problem ?). 

- I tried multiple times and it always fail on the same resource.

- Full output here [logs.txt](https://github.com/adamrehn/ue4-docker/files/11361620/logs.txt)

Did someone manage to build 5.1.1 on linux ?

**Comment by slonopotamus** [comment]
It is either your network issue or something temporary bad with Epic Games CDN. 5.1.1 builds perfectly fine on Linux.

**Comment by keckj** [comment]
The CDN was always failing during docker build but `Setup.sh` was successful on the host. I used advanced build option `source_mode=copy` to fix the problem:
```
ue4-docker build 5.1.1 --target minimal --opt source_mode=copy --combine -layout /tmp/layout
cd /tmp/layout/combined
mkdir ue4 && cd ue4 && git init && git remote add origin "https://github.com/EpicGames/UnrealEngine.git" && git fetch --progress --depth 1 origin "5.1.1-release" && git checkout FETCH_HEAD && ./Setup.sh --exclude=Android --exclude=Mac --exclude=Win32 --exclude=Win64
cd -
docker build --build-arg BASEIMAGE=[custom_base_image] --build-arg SOURCE_LOCATION=ue4
```
