### ISSUE TITLE
Build 5.2 branch fails on file copy stage

### ISSUE THREAD

**Issue by russkel** [adamrehn/ue4-docker#317]
It looks like compiling the engine is successful but when it gets to the point where it is copying files to `LocalBuilds` it fails on creating the directories for `USD`?

I am running a slightly modified `ue4-docker` to get to this stage but it really isn't much (https://github.com/adamrehn/ue4-docker/compare/master...Greenroom-Robotics:ue4-docker:gr)

Does some manifest need to be updated to compile USD or is there some other issue?

```
#19 6890.5 ERROR: Failed to create directory /home/ue4/UnrealEngine/LocalBuilds/Engine/Linux/Engine/Binaries/ThirdParty/USD/UsdResources/Linux/plugins/usdUI/resources for copy
#19 6890.5        while executing task <Copy Files="#Copy for Installed Linux" From="/home/ue4/UnrealEngine" To="/home/ue4/UnrealEngine/LocalBuilds/Engine/Linux" Overwrite="True" Tag="#Installed Build Linux Files" ErrorIfNotFound="False" />
#19 6890.5        at /home/ue4/UnrealEngine/Engine/Build/InstalledEngineBuild.xml(1294)
#19 6890.5        (see /home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/Log.txt for full exception trace)
#19 6890.5 AutomationTool executed for 1h 54m 46s
#19 6890.5 AutomationTool exiting with ExitCode=1 (Error_Unknown)
#19 6890.5 RunUAT ERROR: AutomationTool was unable to run successfully. Exited with code: 1
```

**Comment by slonopotamus** [comment]
I doubt anyone tried to build installed variant of 5.2 yet. Possibly it is just broken.

**Comment by russkel** [comment]
Compiler issues I can figure out, but when it's a bit black box like this I am not sure where to start looking. Doesn't help that it's in a docker build, either.

**Comment by russkel** [comment]
Disregard, this was a disk space issue.
