### ISSUE TITLE
Build Fails to Get Credentials, Firewall Disabled

### ISSUE THREAD

**Issue by bdurepo1** [adamrehn/ue4-docker#34]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.30 (latest available version is 0.0.30)
Operating system:           Linux (Ubuntu 18.04.2 LTS, 4.15.0-49-generic)
Docker daemon version:      18.09.6
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       164.16 GiB
Total system memory:        30.99 GiB physical, 0 bytes virtual
Number of processors:       4 physical, 8 logical

```

```
bdurepo@core:repos$ sudo ue4-docker build 4.20.3 --no-engine
[ue4-docker build] LINUX CONTAINER SETTINGS
[ue4-docker build] Building GPU-enabled images compatible with NVIDIA Docker (OpenGL support).

[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Not excluding any Engine components.

Retrieving the Git credentials that will be used to clone the UE4 repo
Username: bdurepo1
Password: 


[ue4-docker build] Image "adamrehn/ue4-build-prerequisites:opengl" exists and rebuild not requested, skipping build.

[ue4-docker build] Building image "adamrehn/ue4-source:4.20.3-opengl"...
Sending build context to Docker daemon  14.85kB
Step 1/34 : ARG PREREQS_TAG
Step 2/34 : FROM adamrehn/ue4-build-prerequisites:${PREREQS_TAG}
 ---> c9167e5500fe
Step 3/34 : ARG GIT_REPO=""
 ---> Using cache
 ---> a87755bb5fb9
Step 4/34 : ARG GIT_BRANCH=""
 ---> Using cache
 ---> 995912e7daf9
Step 5/34 : ARG HOST_ADDRESS_ARG=""
 ---> Using cache
 ---> b57ab76a16ba
Step 6/34 : ENV HOST_ADDRESS=${HOST_ADDRESS_ARG}
 ---> Using cache
 ---> ba04acc6678f
Step 7/34 : ARG HOST_TOKEN_ARG=""
 ---> Using cache
 ---> e620689e1a59
Step 8/34 : ENV HOST_TOKEN=${HOST_TOKEN_ARG}
 ---> Running in 1eb74ec4e667
Removing intermediate container 1eb74ec4e667
 ---> f3b6a4814083
Step 9/34 : COPY --chown=ue4:ue4 git-credential-helper.sh /tmp/git-credential-helper.sh
 ---> 1e8eb708b9a1
Step 10/34 : ENV GIT_ASKPASS=/tmp/git-credential-helper.sh
 ---> Running in 75dec12db9f9
Removing intermediate container 75dec12db9f9
 ---> 0a185df9c3a6
Step 11/34 : RUN chmod +x /tmp/git-credential-helper.sh && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in 29de28f342e6

RUN directive complete. Docker will now commit the filesystem layer to disk.
Note that for large filesystem layers this can take quite some time.
Performing filesystem layer commit...

Removing intermediate container 29de28f342e6
 ---> 41ae814eb975
Step 12/34 : RUN git clone --progress --depth=1 -b $GIT_BRANCH $GIT_REPO /home/ue4/UnrealEngine && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in c11b2008c0f2
Cloning into '/home/ue4/UnrealEngine'...
error: unable to read askpass response from '/tmp/git-credential-helper.sh'
fatal: could not read Username for 'https://github.com': No such device or address
The command '/bin/sh -c git clone --progress --depth=1 -b $GIT_BRANCH $GIT_REPO /home/ue4/UnrealEngine && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''' returned a non-zero code: 128
[ue4-docker build] Error: failed to build image "adamrehn/ue4-source:4.20.3-opengl".
bdurepo@core:repos$ 
```

Build fails even with firewall disabled

```
bdurepo@core:repos$ sudo ufw status
Status: inactive
```

**Comment by adamrehn** [comment]
@bdurepo1 could you please run the [ue4-docker setup](https://adamrehn.com/docs/ue4-docker/commands/setup) command and see what output that gives you? The firewall detection logic literally just [runs the credential endpoint and tests if a container can access it](https://github.com/adamrehn/ue4-docker/blob/v0.0.30/ue4docker/setup_cmd.py#L10), so even with no firewall running that should still be able to tell you whether the problem is being caused by a connectivity issue between the container and the host.

**Comment by bdurepo1** [comment]
```Creating firewall rule for credential endpoint...
Firewall rule created. Note that the `iptables-persistent` service will need to
be installed for the rule to persist after the host system reboots.```

**Comment by adamrehn** [comment]
Interesting, that output means the connectivity check failed, leading the setup command to believe that a firewall is active. If the firewall is disabled then something else must be blocking the traffic. Could you tell me a bit more about the host configuration please:

- Is this a cloud VM or a local machine?
- What version of Python is being used on the host?
- What is the output of the `docker info` command?

**Comment by bdurepo1** [comment]
I am wondering if it is a DNS issue at this point.

**Comment by adamrehn** [comment]
DNS resolution shouldn't really impact the credential endpoint, since the container communicates with the host system using its IP address, and that address is [determined without using any DNS resolution either](https://github.com/adamrehn/ue4-docker/blob/v0.0.31/ue4docker/infrastructure/NetworkUtils.py). That being said, it might be helpful to check whether the host IP is being determined correctly, since an incorrect address would result in broken connectivity. If you add a print statement to the end of the `NetworkUtils.hostIP()` method and then run the build command, does the correct IP address for the host get printed?

**Comment by vishal-prgmr** [comment]
Hi. I have an issue using the ue4 docker build command because I work under a proxy and I have to set the proxy environment variables. Hence it fails after getting the credentials because without the proxy I cannot access github for cloning.

**Comment by adamrehn** [comment]
@vishal-prgmr have you tried [configuring Docker's proxy settings](https://docs.docker.com/network/proxy/)?

Edited Dockerfiles will be detected if they're located in ue4-docker's package installation directory. The simplest way to make changes is to clone the ue4-docker repository, modify the Dockerfiles in the source tree, and then run `pip3 install .` to install the modified files.
