### ISSUE TITLE
Android build ?

### ISSUE THREAD

**Issue by boskiv** [adamrehn/ue4-docker#46]
Is there an option to build Android build with ue4-docker?

**Comment by adamrehn** [comment]
No, ue4-docker does not currently include cross-compilation support for any target platforms, irrespective of host platform: https://unrealcontainers.com/docs/obtaining-images/image-sources#feature-support-matrix

This is something that I've been considering adding support for in the future, but doing so would require a fairly large redesign of how ue4-docker is structured, so it would be a long-term undertaking rather than something that could be added quickly.

**Comment by dskvr** [comment]
I was planning on using the `ue4-full` [windows] as a base image to other dockerfiles that install the prerequisites for various platforms. In this context of this issue, targeting `android` only really requires the installation of a specific version of `androidstudio` and a few other minor dependencies. Other host dependencies baked into `ue4-full` appear to be in line. Obviously this means that the `ue4` cli utility could not be used in targets other than windows, and instead `batch` scripts would need to be deployed for this purpose. Do you see a problem with this approach?

**Comment by adamrehn** [comment]
@dskvr my understanding is that for Android support to work correctly in an Installed Build of the Engine you need to first install the relevant dependencies (NVIDIA CodeWorks for Android for [Unreal Engine 4.24.3 and older](https://docs.unrealengine.com/en-US/Platforms/Mobile/Android/InstallingAndroidCodeWorksAndroid/index.html) / Android Studio for [Unreal Engine 4.25.0 and newer](https://docs.unrealengine.com/en-US/Support/Builds/ReleaseNotes/4_25/index.html#new:androidndk21bupdate)), include the Android versions of the Engine's third-party dependencies when running `Setup.bat` (i.e. `--include=Android`) and then enable the Android target platform when [creating the Installed Build itself using UAT's BuildGraph script](https://github.com/adamrehn/ue4-docker/blob/v0.0.68/ue4docker/dockerfiles/ue4-minimal/windows/Dockerfile#L26). As such, simply installing Android Studio after the fact will not be sufficient to enable Android support, and you will need to modify the Dockerfiles for the [ue4-build-prerequisites](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-build-prerequisites), [ue4-source](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-source) and [ue4-minimal](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-minimal) container images. The large impact of supporting additional target platforms is one of the motivating factors behind the redesign of ue4-docker being discussed in #48.

**Comment by dskvr** [comment]
Ah, you're absolutely right. Android studio would absolutely need to be included in the build. Thanks for laying it out for me @adamrehn! Also, definitely understand the reasoning behind the redesign, a `dockerfile` generator would definitely make everything quite a bit more flexible and `ue4-docker` would be far easier to maintain.

**Comment by rawatravi** [comment]
did anyone succeed in this ?.if yes please share the steps

**Comment by johannesh** [comment]
I've requested an Epic Grant in order to figure this out and provide a decent guide and ideally a script for anyone to use to build for Android via containers. If anyone else figures it out, I'm also happy to hear about it.

**Comment by percit** [comment]
Is there any update? Or way to build for Android any other way using docker image?
