### ISSUE TITLE
Building dedicated server?

### ISSUE THREAD

**Issue by oxisto** [adamrehn/ue4-docker#49]
Hi, first of all great work on this! However, I am running into problems trying to build my dedicated server. Is it not supported all or am I just missing something here?

I did a regular build of the Docker files using `ue4-docker build 4.22.3`. After running the container and mounting my source folder using:
```
sudo docker run -ti -v /home/path/to/my/game:/source adamrehn/ue4-full:4.22.3
```

and then trying to build a specific configuration (`GameServer`)

```
/home/ue4/UnrealEngine/Engine/Build/BatchFiles/Linux/Build.sh GameServer Linux Development -project=/source/Game.uproject
Fixing inconsistent case in filenames.
Setting up Mono
Building GameServer...
Using 'git status' to determine working set for adaptive non-unity build (/source).
Creating makefile for GameServer (no existing makefile)
ERROR: Couldn't find target rules file for target 'UE4Server' in rules assembly 'UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
       Location: /home/ue4/UnrealEngine/Engine/Intermediate/Build/BuildRules/UE4Rules.dll
       Target rules found:
```

Building using `ue4 build` works, however this only seems to build the `GameEditor` configuration.

Using the `Build.sh` script directly with the `GameEditor` configuration also works, so it seems that somehow the base image does not include the stuff for the `UE4Server` config.

(I've sustituted my game name with just `Game` in the logs)

Any ideas?

Thanks!

**Comment by adamrehn** [comment]
As mentioned in [my comment on this ue4cli issue](https://github.com/adamrehn/ue4cli/issues/7#issuecomment-500102550), Installed Builds of the Unreal Engine (such as that included in the [ue4-full](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-full) container image) don't currently include support for dedicated server targets by default, so you'll need to either use the [ue4-engine](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-engine) image that includes a source build of the Engine, or else modify the BuildGraph XML data to include server target support in the Installed Build produced by the [ue4-minimal](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-minimal) image.

Once [the big refactor of ue4-docker](https://github.com/adamrehn/ue4-docker/issues/48) is done, I'd like to add a feature flag that triggers automatic patching of the BuildGraph XML, so users who want dedicated server support can opt into it, and users who don't need it won't have to worry about increased container image sizes.

**Comment by oxisto** [comment]
Ah ok, I see. I did not find the issue on the cli project when searching for this. So I guess you can close this
