### ISSUE TITLE
add suport to build one container

### ISSUE THREAD

**Issue by Ludea** [adamrehn/ue4-docker#5]
Add support to build one docker container.
To do CI, one image is enough.
For my need, I only need ue4-build.

For example, add `-image` option

**Comment by adamrehn** [comment]
The requested functionality appears to be based on the misunderstanding that each of the built images is completely independent of the others. This is not actually the case: each of the five images that the build script produces uses the previous one as its base, and so each image has a dependency on all of its predecessors.

The following diagram illustrates this dependency chain:

![Diagram depicting image dependency sequence](https://user-images.githubusercontent.com/3490860/43992941-775e270c-9dc9-11e8-8664-b753843a4f61.png)

To build the `ue4-build` image, both the `ue4-build-prerequisities` and `ue4-source` images must also be built. If you do not want the `ue4-package` or `ue4-capture` images, simply specify the flags `--no-package --no-capture` when invoking the build script.

I apologise that the existing documentation did not make the nature of these dependencies clear. I have added the above diagram to the README in the hopes that a pictorial representation will better communicate this information to readers going forward.

Thankyou for taking the time to submit this issue. It's always helpful to receive feedback when particular aspects of the documentation are ambiguous or unclear, and hopefully this comment and the associated README additions will help resolve this question for any other users who run across it.

Cheers,
Adam
