### ISSUE TITLE
Graphics driver for Linux automation tests

### ISSUE THREAD

**Issue by ki11roy** [adamrehn/ue4-docker#52]
I had an issue with running unreal automation tests on linux platform, which I solved by installing oibaf graphics driver:
```
FROM adamrehn/ue4-engine:4.22.3 as builder

USER root
RUN apt-get -y update
RUN apt-get -y install software-properties-common && apt-get -y update

RUN apt-add-repository ppa:oibaf/graphics-drivers && apt-get -y update && apt-get -y dist-upgrade

USER ue4
RUN mkdir /home/ue4/build
WORKDIR /home/ue4/build
ADD --chown=ue4:ue4 . /home/ue4/build

RUN /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildCookRun -utf8output -clientconfig=Development -serverconfig=Development -project=/home/ue4/build/Test.uproject -unattended -nullrhi -noP4 -build -platform=Linux

RUN /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildCookRun -utf8output -project=/home/ue4/build/Test.uproject -run -RunAutomationTests -unattended -nullrhi -NoP4 -ReportOutputPath=/home/ue4/build/Saved/UnitTestsReport
```

Is it possible to add the driver into the base image?

**Comment by adamrehn** [comment]
Performing rendering (or running automation tests that rely on rendering) requires the use of the [NVIDIA Container Toolkit](https://unrealcontainers.com/docs/concepts/nvidia-docker), which mounts the graphics drivers from the host system. As such, it's not necessary (or desirable) to bundle graphics drivers in the container image itself. If you're encountering driver issues then you'll need to update the graphics drivers on the host system that is being used to run the containers.

**Comment by ki11roy** [comment]
Thanks!
