### ISSUE TITLE
Long Filename Support

### ISSUE THREAD

**Issue by seclorum** [adamrehn/ue4-docker#54]
We are using ue4-docker to build our custom UE4 engine, and have discovered that long filename support is not enabled in the Windows image - therefore this is a request to enable this standardly upstream, going forward.  It would be better for us not to fork the project - and probably better for the ue4-docker project in the long run to enable long filenames.

The details for how to do this are here:

https://www.itprotoday.com/windows-10/enable-long-file-name-support-windows-10

Can we humbly request that this be turned on in a future release of ue4-docker?  Thanks!

**Comment by adamrehn** [comment]
Thanks for the suggestion! Long file path support is now enabled for all Windows images in ue4-docker version 0.0.38.

**Comment by seclorum** [comment]
Sweet, works well, thanks for the turnabout.
