### ISSUE TITLE
Fail to find symbol file when running

### ISSUE THREAD

**Issue by wthwlh** [adamrehn/ue4-docker#55]
Output of the `ue4-docker info` command:
N\A
```
FULL OUTPUT OF ue4-docker info GOES HERE
```
N\A
(The rest of the issue description goes here. If you're reporting a problem with building the container images, be sure to include the full output of the `ue4-docker build` command, along with the command line parameters used to invoke the build. If you're making a feature request, you can remove the template contents entirely, since the `ue4-docker info` output is only needed for helping diagnose and reproduce bugs.)

After I build with ue4-full image with ue4 build and ue4 pacakge, my program simply crash after running Foo.sh under LinuxNoEditor folder

4.22.3-5660361+++UE4+Release-4.22 517 0
```bash
Disabling core dumps.
error: XDG_RUNTIME_DIR not set in the environment.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=53392 LargeMemoryPoolOffset=184528 
Failed to find symbol file, expected location:
"/home/ue4/${path to my .uproject}/dist/LinuxNoEditor/myProject/Binaries/Linux/myProject-Linux-Shipping.sym"
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault
```
I checked out running with ue4 runtime image with multiple tags but it appears the same error. This program simply serves as a renderer, so it doesn't need windowed display.

Note: UE4.22.3, Unbuntu 16.04 amd64

**Comment by wthwlh** [comment]
I didn't find "myProject-Linux-Shipping.sym" under any folder though

**Comment by adamrehn** [comment]
By default the [ue4 package](https://adamrehn.com/docs/ue4cli/descriptor-commands/package) command will package a Shipping build of your project, which excludes debug symbols. For debugging purposes, you'll want to build a Development version instead:

```
ue4 package Development
```

The Development build will produce full log output and bundle the relevant symbol files, making it easier to diagnose the cause of the crash.

**Comment by wthwlh** [comment]
@adamrehn Ty for the response. I tried the option with Development with *.sym generated. But the running just has shown the same crash error. May you tell me where to find out how the full crash log? Thanks.

**Comment by adamrehn** [comment]
Under Linux the Unreal Engine should print the full crash log to standard output by default. Can you please post the full commands you're using to start the container and run the packaged project?

**Comment by wthwlh** [comment]
@adamrehn Thanks for the reply, I have figure that out. And both ".sym" file missing "XDG_RUNTIME_DIR not set in the environment" won't crash the program. It turns that I should run ue4-runtime container with "-gpus all" option to suppoort NVIDIA drivers.

**Comment by adamrehn** [comment]
I had suspected that might be the case, which is why I requested the commands so I could determine if any required flags were missing. I'm glad to hear everything is working now.

**Comment by davidtw999** [comment]
Hi @wthwlh, I have the same problem. Could you list the detail how to solve it?

**Comment by TBBle** [comment]
I guess that user was referring to [this documentation](https://docs.docker.com/engine/reference/commandline/run/#gpus) on how to make GPUs available to a container when using `docker run` by adding `--gpus all`.

If you haven't set up for running containers with GPUs available already, you'll want to start [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) and work through until you successfully run the sample workload.

If that doesn't help, I'd suggest opening a new ticket with all the template fully populated, as your issue may only look similar to this one, but be otherwise unrelated.
