### ISSUE TITLE
ue4-docker build 4.22 fails : Can't read from pack stream (CorruptPackFileException)

### ISSUE THREAD

**Issue by remitoudic** [adamrehn/ue4-docker#56]
Output of the `ue4-docker info` command:

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 90
 Server Version: 19.03.4
 Storage Driver: devicemapper
  Pool Name: docker-8:1-7356428-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: ext4
  Udev Sync Supported: true
  Data file: /dev/loop26
  Metadata file: /dev/loop27
  Data loop file: /media/priyanka/Elements/Remi/docker_extern/devicemapper/devicemapper/data
  Metadata loop file: /media/priyanka/Elements/Remi/docker_extern/devicemapper/devicemapper/metadata
  Data Space Used: 33.89GB
  Data Space Total: 107.4GB
  Data Space Available: 73.48GB
  Metadata Space Used: 36.65MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.111GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.145 (2017-11-03)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-32-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 23.52GiB
 Name: yang-Precision-WorkStation-R5500
 ID: 4I6I:DWQR:WLKE:DLWG:EA4Q:VIYT:UMC2:VPQG:FBEQ:5SSJ:THFZ:UPAB
 Docker Root Dir: /media/priyanka/Elements/Remi/docker_extern
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

Hello , 
I want to build the ue4 / Carla project  image on an external disk because of free space issue. 
After passing the following command line : 

ue4-docker build 4.22.2 --no-engine --no-minimal

I get the following Error message at step 28: 

 Step 28/34 : RUN ./Setup.sh && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in 9734d2ffdb00
Registering git hooks... (this will override existing ones!)
Fixing inconsistent case in filenames.
Setting up Mono
Checking dependencies...
Updating dependencies:  18% (12936/41030), 1702.0/9123.9 MiB | 5.04 MiB/s... 
Failed to download 'http://cdn.unrealengine.com/dependencies/3215544-fbbce13ceb6f4aaea59e20af2d659d08/36799aacce147eba397f6eacc7a0f6c9dac946d8': Can't read from pack stream (CorruptPackFileException)
Result: 1
The command '/bin/sh -c ./Setup.sh && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-source:4.22.2-opengl".

I have no idea how to deal with this error. If someone could help me i would be very grateful. 
Thank you in advance
Best 
Rémi

**Comment by adamrehn** [comment]
Hi Rémi,

That error message indicates that one of the downloads was corrupted when retrieving the Unreal Engine's build dependencies. This can happen from time to time when running the setup script, and the usual fix is to simply try again until it works correctly. Make sure you have a stable internet connection and plenty of free disk space, and then re-run the build command.

**Comment by remitoudic** [comment]
Thank you for your good advice . I will try ....  hope at some point that it will work...
