### ISSUE TITLE
Building the full ue4 docker image (minus the engine) has been running for more than 18 hours

### ISSUE THREAD

**Issue by rkaushik840** [adamrehn/ue4-docker#58]
collinsbook@collinsTensorbook:~/UnrealEngine-release$ ue4-docker build 4.23.1 --no-engine --cuda=10.1
[ue4-docker build] LINUX CONTAINER SETTINGS
[ue4-docker build] Building GPU-enabled images compatible with NVIDIA Docker (CUDA 10.1 + OpenGL support).

[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Not excluding any Engine components.

Retrieving the Git credentials that will be used to clone the UE4 repo
Username: rkaushik840
Password: 

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ue4docker/infrastructure/CredentialEndpoint.py", line 72, in _endpoint
    server.run(host='0.0.0.0', port=9876)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 963, in inner
    fd=fd,
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 806, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 699, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

[ue4-docker build] Building image "adamrehn/ue4-build-prerequisites:cudagl10.1"...
Sending build context to Docker daemon  3.072kB
Step 1/7 : ARG BASEIMAGE
Step 2/7 : FROM ${BASEIMAGE}
10.1-devel-ubuntu18.04: Pulling from nvidia/cudagl
35c102085707: Already exists 
251f5509d51d: Already exists 
8e829fe70a46: Already exists 
6001e1789921: Already exists 
9f0a21d58e5d: Already exists 
47b91ac70c27: Already exists 
a0529eb74f28: Already exists 
23bff6dcced5: Already exists 
2137cd2bcba9: Already exists 
63ceb6a83cec: Pull complete 
0003c4bc3992: Pull complete 
6f824d38152d: Pull complete 
8ea9f2b1b971: Pull complete 
85e92521922e: Pull complete 
Digest: sha256:ae973a3726b12a07e73ba5d8359cde31fd13a3dbbe01175491698f11a2c3b760
Status: Downloaded newer image for nvidia/cudagl:10.1-devel-ubuntu18.04
 ---> 33b09b74bace
Step 3/7 : LABEL com.adamrehn.ue4-docker.sentinel="1"
 ---> Running in 932b492dbe11
Removing intermediate container 932b492dbe11
 ---> 29b261ff8061
Step 4/7 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Running in b3b1e9dcb1d1
Removing intermediate container b3b1e9dcb1d1
 ---> 5321142ae751
Step 5/7 : RUN 	apt-get update && apt-get install -y --no-install-recommends 		build-essential 		ca-certificates 		curl 		git 		python3 		python3-pip 		shared-mime-info 		tzdata 		unzip 		xdg-user-dirs 		zip && 	rm -rf /var/lib/apt/lists/* && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in ffba0a85f2a0
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:3 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [564 B]
Get:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [819 B]
Get:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Get:8 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [119 kB]
Get:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [22.3 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/restricted i386 Packages [5385 B]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [784 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [6224 B]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [754 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [508 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:19 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [16.3 kB]
Get:20 http://security.ubuntu.com/ubuntu bionic-security/multiverse i386 Packages [4510 B]
Get:21 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [725 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic/universe i386 Packages [11.3 MB]
Get:23 http://archive.ubuntu.com/ubuntu bionic/main i386 Packages [1328 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:25 http://archive.ubuntu.com/ubuntu bionic/restricted i386 Packages [13.5 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic/multiverse i386 Packages [177 kB]
Get:28 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:29 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [1265 kB]
Get:30 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [9571 B]
Get:31 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse i386 Packages [7581 B]
Get:32 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [796 kB]
Get:33 http://archive.ubuntu.com/ubuntu bionic-updates/restricted i386 Packages [13.6 kB]
Get:34 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [29.9 kB]
Get:35 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1030 kB]
Get:36 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1312 kB]
Get:37 http://archive.ubuntu.com/ubuntu bionic-backports/main i386 Packages [2493 B]
Get:38 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2496 B]
Get:39 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4234 B]
Get:40 http://archive.ubuntu.com/ubuntu bionic-backports/universe i386 Packages [4239 B]
Fetched 33.6 MB in 30s (1110 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.4ubuntu1).
build-essential set to manually installed.
ca-certificates is already the newest version (20180409).
The following additional packages will be installed:
  git-man libcurl3-gnutls libcurl4 liberror-perl libgssapi-krb5-2 libk5crypto3
  libkeyutils1 libkrb5-3 libkrb5support0 libmpdec2 libnghttp2-14 libpsl5
  libpython3-stdlib libpython3.6-minimal libpython3.6-stdlib librtmp1
  mime-support python-pip-whl python3-distutils python3-lib2to3
  python3-minimal python3.6 python3.6-minimal
Suggested packages:
  gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email
  git-gui gitk gitweb git-cvs git-mediawiki git-svn krb5-doc krb5-user
  python3-doc python3-tk python3-venv python3.6-venv python3.6-doc
  binfmt-support
Recommended packages:
  less ssh-client krb5-locales publicsuffix file python3-dev
  python3-setuptools python3-wheel
The following NEW packages will be installed:
  curl git git-man libcurl3-gnutls libcurl4 liberror-perl libgssapi-krb5-2
  libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libmpdec2 libnghttp2-14
  libpsl5 libpython3-stdlib libpython3.6-minimal libpython3.6-stdlib librtmp1
  mime-support python-pip-whl python3 python3-distutils python3-lib2to3
  python3-minimal python3-pip python3.6 python3.6-minimal shared-mime-info
  tzdata unzip xdg-user-dirs zip
0 upgraded, 32 newly installed, 0 to remove and 52 not upgraded.
Need to get 13.3 MB of archives.
After this operation, 73.2 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6-minimal amd64 3.6.8-1~18.04.3 [533 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3.6-minimal amd64 3.6.8-1~18.04.3 [1610 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3-minimal amd64 3.6.7-1~18.04 [23.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 mime-support all 3.60ubuntu1 [30.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 libmpdec2 amd64 2.4.2-1ubuntu1 [84.1 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6-stdlib amd64 3.6.8-1~18.04.3 [1712 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3.6 amd64 3.6.8-1~18.04.3 [202 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3-stdlib amd64 3.6.7-1~18.04 [7240 B]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3 amd64 3.6.7-1~18.04 [47.2 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 shared-mime-info amd64 1.9-2 [426 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 tzdata all 2019c-0ubuntu0.18.04 [190 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/main amd64 xdg-user-dirs amd64 0.17-1ubuntu1 [48.0 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libkrb5support0 amd64 1.16-2ubuntu0.1 [30.9 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libk5crypto3 amd64 1.16-2ubuntu0.1 [85.6 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/main amd64 libkeyutils1 amd64 1.5.9-9.2ubuntu2 [8720 B]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libkrb5-3 amd64 1.16-2ubuntu0.1 [279 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgssapi-krb5-2 amd64 1.16-2ubuntu0.1 [122 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpsl5 amd64 0.19.1-5build1 [41.8 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic/main amd64 libnghttp2-14 amd64 1.30.0-1ubuntu1 [77.8 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-1 [54.2 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcurl4 amd64 7.58.0-2ubuntu3.8 [214 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 curl amd64 7.58.0-2ubuntu3.8 [159 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcurl3-gnutls amd64 7.58.0-2ubuntu3.8 [213 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic/main amd64 liberror-perl all 0.17025-1 [22.8 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 git-man all 1:2.17.1-1ubuntu0.4 [803 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 git amd64 1:2.17.1-1ubuntu0.4 [3907 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python-pip-whl all 9.0.1-2.3~ubuntu1.18.04.1 [1653 kB]
Get:28 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3-lib2to3 all 3.6.9-1~18.04 [77.4 kB]
Get:29 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3-distutils all 3.6.9-1~18.04 [144 kB]
Get:30 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python3-pip all 9.0.1-2.3~ubuntu1.18.04.1 [114 kB]
Get:31 http://archive.ubuntu.com/ubuntu bionic/main amd64 unzip amd64 6.0-21ubuntu1 [167 kB]
Get:32 http://archive.ubuntu.com/ubuntu bionic/main amd64 zip amd64 3.0-11build1 [167 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 13.3 MB in 1min 9s (191 kB/s)
Selecting previously unselected package libpython3.6-minimal:amd64.
(Reading database ... 14210 files and directories currently installed.)
Preparing to unpack .../libpython3.6-minimal_3.6.8-1~18.04.3_amd64.deb ...
Unpacking libpython3.6-minimal:amd64 (3.6.8-1~18.04.3) ...
Selecting previously unselected package python3.6-minimal.
Preparing to unpack .../python3.6-minimal_3.6.8-1~18.04.3_amd64.deb ...
Unpacking python3.6-minimal (3.6.8-1~18.04.3) ...
Setting up libpython3.6-minimal:amd64 (3.6.8-1~18.04.3) ...
Setting up python3.6-minimal (3.6.8-1~18.04.3) ...
Selecting previously unselected package python3-minimal.
(Reading database ... 14449 files and directories currently installed.)
Preparing to unpack .../0-python3-minimal_3.6.7-1~18.04_amd64.deb ...
Unpacking python3-minimal (3.6.7-1~18.04) ...
Selecting previously unselected package mime-support.
Preparing to unpack .../1-mime-support_3.60ubuntu1_all.deb ...
Unpacking mime-support (3.60ubuntu1) ...
Selecting previously unselected package libmpdec2:amd64.
Preparing to unpack .../2-libmpdec2_2.4.2-1ubuntu1_amd64.deb ...
Unpacking libmpdec2:amd64 (2.4.2-1ubuntu1) ...
Selecting previously unselected package libpython3.6-stdlib:amd64.
Preparing to unpack .../3-libpython3.6-stdlib_3.6.8-1~18.04.3_amd64.deb ...
Unpacking libpython3.6-stdlib:amd64 (3.6.8-1~18.04.3) ...
Selecting previously unselected package python3.6.
Preparing to unpack .../4-python3.6_3.6.8-1~18.04.3_amd64.deb ...
Unpacking python3.6 (3.6.8-1~18.04.3) ...
Selecting previously unselected package libpython3-stdlib:amd64.
Preparing to unpack .../5-libpython3-stdlib_3.6.7-1~18.04_amd64.deb ...
Unpacking libpython3-stdlib:amd64 (3.6.7-1~18.04) ...
Setting up python3-minimal (3.6.7-1~18.04) ...
Selecting previously unselected package python3.
(Reading database ... 14879 files and directories currently installed.)
Preparing to unpack .../00-python3_3.6.7-1~18.04_amd64.deb ...
Unpacking python3 (3.6.7-1~18.04) ...
Selecting previously unselected package shared-mime-info.
Preparing to unpack .../01-shared-mime-info_1.9-2_amd64.deb ...
Unpacking shared-mime-info (1.9-2) ...
Selecting previously unselected package tzdata.
Preparing to unpack .../02-tzdata_2019c-0ubuntu0.18.04_all.deb ...
Unpacking tzdata (2019c-0ubuntu0.18.04) ...
Selecting previously unselected package xdg-user-dirs.
Preparing to unpack .../03-xdg-user-dirs_0.17-1ubuntu1_amd64.deb ...
Unpacking xdg-user-dirs (0.17-1ubuntu1) ...
Selecting previously unselected package libkrb5support0:amd64.
Preparing to unpack .../04-libkrb5support0_1.16-2ubuntu0.1_amd64.deb ...
Unpacking libkrb5support0:amd64 (1.16-2ubuntu0.1) ...
Selecting previously unselected package libk5crypto3:amd64.
Preparing to unpack .../05-libk5crypto3_1.16-2ubuntu0.1_amd64.deb ...
Unpacking libk5crypto3:amd64 (1.16-2ubuntu0.1) ...
Selecting previously unselected package libkeyutils1:amd64.
Preparing to unpack .../06-libkeyutils1_1.5.9-9.2ubuntu2_amd64.deb ...
Unpacking libkeyutils1:amd64 (1.5.9-9.2ubuntu2) ...
Selecting previously unselected package libkrb5-3:amd64.
Preparing to unpack .../07-libkrb5-3_1.16-2ubuntu0.1_amd64.deb ...
Unpacking libkrb5-3:amd64 (1.16-2ubuntu0.1) ...
Selecting previously unselected package libgssapi-krb5-2:amd64.
Preparing to unpack .../08-libgssapi-krb5-2_1.16-2ubuntu0.1_amd64.deb ...
Unpacking libgssapi-krb5-2:amd64 (1.16-2ubuntu0.1) ...
Selecting previously unselected package libpsl5:amd64.
Preparing to unpack .../09-libpsl5_0.19.1-5build1_amd64.deb ...
Unpacking libpsl5:amd64 (0.19.1-5build1) ...
Selecting previously unselected package libnghttp2-14:amd64.
Preparing to unpack .../10-libnghttp2-14_1.30.0-1ubuntu1_amd64.deb ...
Unpacking libnghttp2-14:amd64 (1.30.0-1ubuntu1) ...
Selecting previously unselected package librtmp1:amd64.
Preparing to unpack .../11-librtmp1_2.4+20151223.gitfa8646d.1-1_amd64.deb ...
Unpacking librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1) ...
Selecting previously unselected package libcurl4:amd64.
Preparing to unpack .../12-libcurl4_7.58.0-2ubuntu3.8_amd64.deb ...
Unpacking libcurl4:amd64 (7.58.0-2ubuntu3.8) ...
Selecting previously unselected package curl.
Preparing to unpack .../13-curl_7.58.0-2ubuntu3.8_amd64.deb ...
Unpacking curl (7.58.0-2ubuntu3.8) ...
Selecting previously unselected package libcurl3-gnutls:amd64.
Preparing to unpack .../14-libcurl3-gnutls_7.58.0-2ubuntu3.8_amd64.deb ...
Unpacking libcurl3-gnutls:amd64 (7.58.0-2ubuntu3.8) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../15-liberror-perl_0.17025-1_all.deb ...
Unpacking liberror-perl (0.17025-1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../16-git-man_1%3a2.17.1-1ubuntu0.4_all.deb ...
Unpacking git-man (1:2.17.1-1ubuntu0.4) ...
Selecting previously unselected package git.
Preparing to unpack .../17-git_1%3a2.17.1-1ubuntu0.4_amd64.deb ...
Unpacking git (1:2.17.1-1ubuntu0.4) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../18-python-pip-whl_9.0.1-2.3~ubuntu1.18.04.1_all.deb ...
Unpacking python-pip-whl (9.0.1-2.3~ubuntu1.18.04.1) ...
Selecting previously unselected package python3-lib2to3.
Preparing to unpack .../19-python3-lib2to3_3.6.9-1~18.04_all.deb ...
Unpacking python3-lib2to3 (3.6.9-1~18.04) ...
Selecting previously unselected package python3-distutils.
Preparing to unpack .../20-python3-distutils_3.6.9-1~18.04_all.deb ...
Unpacking python3-distutils (3.6.9-1~18.04) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../21-python3-pip_9.0.1-2.3~ubuntu1.18.04.1_all.deb ...
Unpacking python3-pip (9.0.1-2.3~ubuntu1.18.04.1) ...
Selecting previously unselected package unzip.
Preparing to unpack .../22-unzip_6.0-21ubuntu1_amd64.deb ...
Unpacking unzip (6.0-21ubuntu1) ...
Selecting previously unselected package zip.
Preparing to unpack .../23-zip_3.0-11build1_amd64.deb ...
Unpacking zip (3.0-11build1) ...
Setting up python-pip-whl (9.0.1-2.3~ubuntu1.18.04.1) ...
Setting up git-man (1:2.17.1-1ubuntu0.4) ...
Setting up libnghttp2-14:amd64 (1.30.0-1ubuntu1) ...
Setting up mime-support (3.60ubuntu1) ...
Setting up liberror-perl (0.17025-1) ...
Setting up libpsl5:amd64 (0.19.1-5build1) ...
Setting up tzdata (2019c-0ubuntu0.18.04) ...

Current default time zone: 'Etc/UTC'
Local time is now:      Wed Nov 13 19:11:12 UTC 2019.
Universal Time is now:  Wed Nov 13 19:11:12 UTC 2019.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Setting up unzip (6.0-21ubuntu1) ...
Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1) ...
Setting up libkrb5support0:amd64 (1.16-2ubuntu0.1) ...
Setting up zip (3.0-11build1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up shared-mime-info (1.9-2) ...
Setting up libkeyutils1:amd64 (1.5.9-9.2ubuntu2) ...
Setting up xdg-user-dirs (0.17-1ubuntu1) ...
Setting up libmpdec2:amd64 (2.4.2-1ubuntu1) ...
Setting up libpython3.6-stdlib:amd64 (3.6.8-1~18.04.3) ...
Setting up libk5crypto3:amd64 (1.16-2ubuntu0.1) ...
Setting up python3.6 (3.6.8-1~18.04.3) ...
Setting up libkrb5-3:amd64 (1.16-2ubuntu0.1) ...
Setting up libpython3-stdlib:amd64 (3.6.7-1~18.04) ...
Setting up python3 (3.6.7-1~18.04) ...
Setting up libgssapi-krb5-2:amd64 (1.16-2ubuntu0.1) ...
Setting up python3-lib2to3 (3.6.9-1~18.04) ...
Setting up python3-distutils (3.6.9-1~18.04) ...
Setting up libcurl3-gnutls:amd64 (7.58.0-2ubuntu3.8) ...
Setting up libcurl4:amd64 (7.58.0-2ubuntu3.8) ...
Setting up python3-pip (9.0.1-2.3~ubuntu1.18.04.1) ...
Setting up git (1:2.17.1-1ubuntu0.4) ...
Setting up curl (7.58.0-2ubuntu3.8) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...

RUN directive complete. Docker will now commit the filesystem layer to disk.
Note that for large filesystem layers this can take quite some time.
Performing filesystem layer commit...

Removing intermediate container ffba0a85f2a0
 ---> 526c8773b301
Step 6/7 : RUN 	useradd --create-home --home /home/ue4 --shell /bin/bash --uid 1000 ue4 && 	usermod -a -G audio,video ue4 && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in 754876bc2340

RUN directive complete. Docker will now commit the filesystem layer to disk.
Note that for large filesystem layers this can take quite some time.
Performing filesystem layer commit...

Removing intermediate container 754876bc2340
 ---> 1eda970923fd
Step 7/7 : USER ue4
 ---> Running in 16215d94b6ad
Removing intermediate container 16215d94b6ad
 ---> fdc4e8b32c77
Successfully built fdc4e8b32c77
Successfully tagged adamrehn/ue4-build-prerequisites:cudagl10.1
[ue4-docker build] Built image "adamrehn/ue4-build-prerequisites:cudagl10.1" in 2 minutes and 32.77 seconds

[ue4-docker build] Building image "adamrehn/ue4-source:4.23.1-cudagl10.1"...
Sending build context to Docker daemon  14.85kB
Step 1/34 : ARG PREREQS_TAG
Step 2/34 : FROM adamrehn/ue4-build-prerequisites:${PREREQS_TAG}
 ---> fdc4e8b32c77
Step 3/34 : ARG GIT_REPO=""
 ---> Running in d3b5a0ef0a7c
Removing intermediate container d3b5a0ef0a7c
 ---> c873989d4946
Step 4/34 : ARG GIT_BRANCH=""
 ---> Running in ab9c5d8a8fb8
Removing intermediate container ab9c5d8a8fb8
 ---> 94ff64ff2966
Step 5/34 : ARG HOST_ADDRESS_ARG=""
 ---> Running in d7c479a1a51c
Removing intermediate container d7c479a1a51c
 ---> d4bee7796ba3
Step 6/34 : ENV HOST_ADDRESS=${HOST_ADDRESS_ARG}
 ---> Running in 066460ec2acf
Removing intermediate container 066460ec2acf
 ---> 3f2ed4e69a99
Step 7/34 : ARG HOST_TOKEN_ARG=""
 ---> Running in febbaa0f072a
Removing intermediate container febbaa0f072a
 ---> 92fc0b4a0a33
Step 8/34 : ENV HOST_TOKEN=${HOST_TOKEN_ARG}
 ---> Running in 33b2da2ab014
Removing intermediate container 33b2da2ab014
 ---> 0c03e9bb74c1
Step 9/34 : COPY --chown=ue4:ue4 git-credential-helper.sh /tmp/git-credential-helper.sh
 ---> 9b25fa3ceffd
Step 10/34 : ENV GIT_ASKPASS=/tmp/git-credential-helper.sh
 ---> Running in ae144a75cf2f
Removing intermediate container ae144a75cf2f
 ---> ac4e36af5658
Step 11/34 : RUN chmod +x /tmp/git-credential-helper.sh && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in 3bea20185a9f

RUN directive complete. Docker will now commit the filesystem layer to disk.
Note that for large filesystem layers this can take quite some time.
Performing filesystem layer commit...

Removing intermediate container 3bea20185a9f
 ---> 6a2a72b02f4e
Step 12/34 : RUN git clone --progress --depth=1 -b $GIT_BRANCH $GIT_REPO /home/ue4/UnrealEngine && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in c0fb4b965745
Cloning into '/home/ue4/UnrealEngine'...

I have left the process running here for 18+ hours but it is still not moving ahead. 
I am building the images for Unreal Engine ver. 4.23.1 using CUDA 10.1
My System Config are:
32 GB RAM
837 GB of available disk space for large filesystem.
GeForce RTX 2080 with Max-Q Design/PCIe/SSE2
GNOME: 3.28.2
OS Type: 64 bit
Intel Core i7-970H CPU @ 2.6GHz x 12
Ubuntu 18.04 LTS  (Bionic Beaver)
ue4-docker version: 0.0.40
I already have NVIDIA Docker Runtime Toolkit running successfully

Please help at the earliest. Thank you!

(The rest of the issue description goes here. If you're reporting a problem with building the container images, be sure to include the full output of the `ue4-docker build` command, along with the command line parameters used to invoke the build. If you're making a feature request, you can remove the template contents entirely, since the `ue4-docker info` output is only needed for helping diagnose and reproduce bugs.)

**Comment by adamrehn** [comment]
The traceback at the start shows the cause of the problem:

```
Traceback (most recent call last):
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.6/dist-packages/ue4docker/infrastructure/CredentialEndpoint.py", line 72, in _endpoint
server.run(host='0.0.0.0', port=9876)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 990, in run
run_simple(host, port, self, **options)
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 1010, in run_simple
inner()
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 963, in inner
fd=fd,
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 806, in make_server
host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 699, in init
HTTPServer.init(self, server_address, handler)
File "/usr/lib/python3.6/socketserver.py", line 456, in init
self.server_bind()
File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
socketserver.TCPServer.server_bind(self)
File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

The credential endpoint has failed to start because some other process has bound TCP port 9876, and the `git clone` command is hanging indefinitely waiting to receive credentials. You will need to cancel the build, free up TCP port 9876, and start the build again.

I've added a check in commit 2383ea2 (live in ue4-docker version 0.0.41) that makes the build abort if the credential endpoint cannot be started, rather than allowing it to hang indefinitely, which will prevent anyone else from finding themselves in a similar situation.
