### ISSUE TITLE
Cuda Version 10.2 released

### ISSUE THREAD

**Issue by Clockwork-Muse** [adamrehn/ue4-docker#59]
Cuda Version 10.2 images released 2019-11-27

**Comment by adamrehn** [comment]
Thanks! Fix is live in ue4-docker version 0.0.43.

**Comment by Clockwork-Muse** [comment]
I posted this, but despite the overview showing them, [it turns out the tags don't exist](https://gitlab.com/nvidia/container-images/cuda/issues/59).

**Comment by adamrehn** [comment]
Looks like they're live now, so they should work with ue4-docker.

**Comment by adamrehn** [comment]
CUDA 10.2 variants of the [ue4-runtime](https://github.com/adamrehn/ue4-runtime) image are now also live.
