### ISSUE TITLE
stuck at step 4

### ISSUE THREAD

**Issue by Ludea** [adamrehn/ue4-docker#6]
Hello,

I try to build the images, but when I start, the script stop a step 4 (when downloading chocolatey)
The error message is :
`
container cab21ffabd06d2b99b7ab58f85ee90c13e27576eeed8c5b2c1c223e80a641328 encountered an error during CreateContainer: failure in a Windows system call: This operation ended because the timeout has expired. (0x5b4) extra info: {"SystemType":"Container","Name":"cab21ffabd06d2b99b7ab58f85ee90c13e27576eeed8c5b2c1c223e80a641328","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\cab21ffabd06d2b99b7ab58f85ee90c13e27576eeed8c5b2c1c223e80a641328","Layers":[{"ID":"d804ac4b-2bc6-512a-92ce-56af3edf226a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f94c476f6913d91cca715fce4cad82891183b5ee47b643b8d148fc819f631ec7"},{"ID":"b1c2c847-85f6-50cc-a7f6-b3c8e90df080","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e7c226e6a949f2c321c2018f07a3fd547a95c1e81a313e5effcd206b075c8e3e"},{"ID":"8a0a78ba-0340-539d-8a9d-98b0ed2b52ab","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1dfd13f1bf8c6aab6eecf737a889f958c585049bc2ef97436e5c5b8358320cfc"},{"ID":"b32ef9d1-ec7d-5ab2-8607-05824b3c9b31","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d02ba949a21c65f8ea566f2516e9f4f297916228b9ffe6404685fcd1ceecf6ae"},{"ID":"dcc9f81d-df80-581d-9d76-9d7598449060","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dc6afd315baa82d9076a6505f417c8673b3684452b8957bc022e12d36dc5a49f"},{"ID":"edf48f0b-f8e7-5770-aba8-03eb49fc0fac","Path":"C:\\ProgramData\\Docker\\windowsfilter\\df07c39ab323a46698034e3577a161d097d9ccbdce11ed70f96d616596b29afc"},{"ID":"fa933a97-3692-55f9-9440-2bcbf656fb49","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e58d89d71399cbc91b5a242d636d1aca7248d06ffdc8cc0ec9c4bcdd44dd4b65"},{"ID":"0aed8c5f-c558-5774-8270-ec86957ae7dd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\bd05a7709f9f7f5466d0a3f8df5cd9a5421762ea397c392dff3dd22bb510f4c9"},{"ID":"2f2b29f3-ccf6-505d-b20f-165679a30343","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6ad1cf9f2b31a1f02739336ee465f59bc69f1c1c9db90f5ebe66f762f11e9fdd"},{"ID":"051a47ff-56cd-5e60-90da-e3cc039bf9a3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\fad12a062cd9cb672b366b6a2c4fc3b9e11dc3f953384d19adb29cce8a0d5d62"},{"ID":"0a7c4c09-4514-5b57-b5f9-d2c53c6dab22","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f695ed66d8f52b33070dba89d4f4f8819ba3c10e62ab56211b6de6e381e4e925"},{"ID":"6c2ede93-cbdb-512c-9e54-0c8c9aba000b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\24a54245899050ee869866017dd222b86025a8ab24b0741a72694f84df2edf43"},{"ID":"f52646a5-2d85-5088-87fa-868384d269c7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dcf8ea9319e12c961a72642da985ee48b8b5ced74d4c40f4b386c03adc82f8f5"},{"ID":"20b74dda-da9a-51df-a4b8-0c878b9b601f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6d6aad76efce8f76996a740c7f803044a35a481dbb420a77b05bf2e117485b95"},{"ID":"41ef1358-36ae-5bb1-9ef9-0ac152fd6be8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4d867abc47bbc4a62453ac13b805fcd2503c854f40c56b2b20f2537e05c662c0"}],"MemoryMaximumInMB":9420,"HostName":"cab21ffabd06","HvPartition":true,"EndpointList":["7659b812-da6b-4728-8ccd-25c813aecd4b"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\6d6aad76efce8f76996a740c7f803044a35a481dbb420a77b05bf2e117485b95\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}
`

Any idea ?

**Comment by adamrehn** [comment]
If the build is running under Windows 10 (or under Windows Server using Hyper-V isolation mode) then this error might be related to the infamous [`hcsshim` timeout errors](https://github.com/adamrehn/ue4-docker#windows-hcsshim-timeout-issues) that have been encountered previously.

To determine if this is the case, can you please attempt to run the build script again using the `--random-memory` flag, re-running the script each time a failure occurs? If the previously-failing step suddenly works on one of the retries, only to have the build then fail on a subsequent step, then the root issue is likely the same as the `hcsshim` timeout error and I will update the documentation accordingly.

**Comment by Ludea** [comment]
I build under Windows 10 version 1803.
The command I use is : `python build.py --no-package --no-capture --random-memory 4.20.1`
I try a lot of time and still stuck at step 4.

**Comment by adamrehn** [comment]
How many times is a lot? In the past, there have been instances when I've had to re-run the command well over a dozen times before build progress is able to resume after encountering an `hcsshim` timeout error, and in some instances it has also been necessary to restart the Docker daemon and even restart Windows itself before progress is able to resume. (If you think that sounds unreasonable, I happen to agree. Hyper-V isolation mode is so fundamentally broken at this point in time that I have resorted to using process isolation mode under Windows Server to build and test the Windows container images until Microsoft fixes the problem.)

**Comment by Ludea** [comment]
I try about 10 times.
Do you prefer use Windows server ? I can switch to it and  test build ( with -isolation=process)

**Comment by adamrehn** [comment]
Yes, I find that process isolation mode under Windows Server works quite well, and that the performance is also noticeably better than under Hyper-V isolation mode. When running under Windows Server, process isolation mode is the default mode, so you won't even need to explicitly specify the `-isolation` flag, it should use process isolation automatically. It is worth noting that the kernel version targeted by the containers being built must match the kernel version of the host operating system when process isolation is being used, but you don't need to worry about specifying this manually either since the latest version of the build script will take care of setting this for you automatically.

**Comment by Ludea** [comment]
I switch to windows server 1804, the build works perfectly!
