### ISSUE TITLE
adamrehn/ue4-build-prerequisites:ltsc2019 on DockerHub missing 32-bit MSVC Runtime

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4-docker#69]
Observed while trying to build ue4-minimal with ltsc2019 basetag, and `--pull-prequisites` specified.

Reproduction log:
```
PS C:\Users\localadmin> docker pull adamrehn/ue4-build-prerequisites:ltsc2019
ltsc2019: Pulling from adamrehn/ue4-build-prerequisites
...
Digest: sha256:a67f1a41a55a93b7e9d7f520c22b2f90020009e1ea1e51b3c3052c1a08a00718
Status: Downloaded newer image for adamrehn/ue4-build-prerequisites:ltsc2019
docker.io/adamrehn/ue4-build-prerequisites:ltsc2019
```
```
PS C:\Users\localadmin> docker run --rm -ti adamrehn/ue4-build-prerequisites:ltsc2019
Microsoft Windows [Version 10.0.17763.805]
(c) 2018 Microsoft Corporation. All rights reserved.
```
```
C:\> C:\BuildTools\MSBuild\15.0\Bin\MSBuild.exe /?

```
```
C:\> C:\BuildTools\MSBuild\15.0\Bin\amd64\MSBuild.exe /?
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
... Rest of the help output
```
```
C:\>pip install dll-diagnostics
Collecting dll-diagnostics
...
Successfully installed Pygments-2.5.2 bleach-3.1.0 certifi-2019.11.28 chardet-3.0.4 colorama-0.4.3 dll-diagnostics-0.0.3 docutils-0.16 future-0.18.2 idna-2.8 importlib-metadata-1.5.0 keyring-21.1.0 pefile-2019.4.18 pkginfo-1.5.0.1 pywin32-227 pywin32-ctypes-0.2.0 readme-renderer-24.0 requests-2.22.0 requests-toolbelt-0.9.1 six-1.14.0 termcolor-1.1.0 tqdm-4.42.1 twine-3.1.1 urllib3-1.25.8 webencodings-0.5.1 wheel-0.34.2 zipp-3.0.0
```
```
C:\>dlldiag deps C:\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
DLL Diagnostic Tools version 0.0.3
Copyright (c) 2019 Adam Rehn

Parsing module header and identifying direct dependencies... done.

Parsed module details:
Module:          C:\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
Type:            Executable
Architecture:    x86

Attempting to load the module's direct dependencies:

Error: cannot run the helper executable for architecture x86. Please ensure the Microsoft Visual C++ Redistributable for Visual Studio 2015-201
9 is installed correctly.

```
```
C:\>dlldiag deps C:\BuildTools\MSBuild\15.0\Bin\amd64\MSBuild.exe
DLL Diagnostic Tools version 0.0.3
Copyright (c) 2019 Adam Rehn

Parsing module header and identifying direct dependencies... done.

Parsed module details:
Module:          C:\BuildTools\MSBuild\15.0\Bin\amd64\MSBuild.exe
Type:            Executable
Architecture:    x64

No dependencies detected.
```

**Comment by TBBle** [comment]
I reckon this was a bad report, and I've hit https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im by having the Febuary 2020 security patch on the host, but not on the contained image.

I've tried a few other ltsc2019 images, and they're showing similar issues, e.g., https://hub.docker.com/r/stefanscherer/chocolatey/tags which is showing the 'immediate exit' issue on binaries that are already in the image.

It's a bit tricky to verify, since MS have helpfully locked the `ltsc2019` tag to the January Security fix.

```
PS C:\Users\localadmin> docker info
Client:
 Debug Mode: false
 Plugins:
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-app.exe" is not valid: failed to fetch metadata: exit status 1
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-assemble.exe" is not valid: failed to fetch metadata: exit status 1
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-cluster.exe" is not valid: failed to fetch metadata: exit status 1
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-registry.exe" is not valid: failed to fetch metadata: exit status 1
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-template.exe" is not valid: failed to fetch metadata: exit status 1

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 73
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.1039)
 OSType: windows
 Architecture: x86_64
 CPUs: 40
 Total Memory: 63.89GiB
 Name: au1-bldwin-22
 ID: UP5E:LFL5:QLL7:USJO:XDC7:SGFK:YL5L:K24K:6BZE:YG6F:DQMR:I3WU
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
```
PS C:\Users\localadmin> python -m ue4docker info
ue4-docker version:         0.0.52 (latest available version is 0.0.52)
Operating system:           Windows Server 2019 Standard Version 1809 (OS Build 17763.1039)
Docker daemon version:      19.03.5
NVIDIA Docker supported:    No
Maximum image size:         200GB
Available disk space:       723.98 GiB
Total system memory:        63.89 GiB physical, 73.39 GiB virtual
Number of processors:       20 physical, 40 logical
```

**Comment by adamrehn** [comment]
Given that the build prerequisites image definitely contains [all available Visual C++ runtimes](https://github.com/adamrehn/ue4-docker/blob/v0.0.52/ue4docker/dockerfiles/ue4-build-prerequisites/windows/install-prerequisites.bat#L3), I'd agree that this is most likely a host configuration issue. It's a bit worrying to see a Windows security patch cause problems inside containers like that, hopefully Microsoft will get it resolved before I have to start checking for the presence of that patch and blacklisting the host in the same manner that ue4-docker currently blacklists Windows versions 1903 and 1909.

**Comment by TBBle** [comment]
Hmm. There's no image for `mcr.microsoft.com/dotnet/framework/sdk:4.7.2-windowsservercore-10.0.17763.1039`, so I can't actually hack around this for ue4-docker. -_-

**Comment by TBBle** [comment]
Yeah, it is a worry. I only found it because I was frustrated and looking at their page on Dockerhub. I'd never have otherwise hit it, since it looks just like a 'missing DLL' issue, even down to returning `STATUS_DLL_INIT_FAILED`.

**Comment by adamrehn** [comment]
Yeah, Microsoft seem to have stopped publishing new images for version 4.7.2 of the .NET framework. Once the next SAC release of Windows comes out I'm going to be forced to change to a newer version of .NET (at least for newer OS base image tags.)

I recall a similarly frustrating bug that affected `xcopy` under Windows Server 2016, whereby it would just silently fail. To this day all the copy commands in the Windows Dockerfiles use a Python script to provide the equivalent functionality to ensure compatibility with older versions of Windows.

**Comment by TBBle** [comment]
Looking at https://mcr.microsoft.com/v2/dotnet/framework/sdk/tags/list, I think they haven't built *any* of the .NET SDK images for specific server builds, only for the tagged builds. I ended up uninstalling the security update ([KB4532691](https://support.microsoft.com/en-au/help/4532691)) and a build with `--pull-prerequisites` is going now.

The initial symptom, for the record, is that without failures, _AutomationToolLauncher.exe_ wasn't built, because MSBuild.exe was suffering the silent-exit issue. So the first call to RunUAT.bat failed trying to run _AutomationToolLauncher.exe_.

**Comment by adamrehn** [comment]
Looking through the JSON from that link, I can see that the .NET Framework version 4.8 is in fact provided for all currently supported "floating" base tags, which confirms my suspicion that it's only older .NET versions that aren't getting the newer tags:

```
"4.8-windowsservercore-1803",
"4.8-windowsservercore-1903",
"4.8-windowsservercore-1909",
"4.8-windowsservercore-ltsc2016",
"4.8-windowsservercore-ltsc2019",
```

Let me know how you go with the new build now that the KB has been uninstalled.

**Comment by TBBle** [comment]
I just checked, it's definitely past the point it was stuck on before, and is actively compiling things. So I believe uninstalling worked.

It also looks like we'd done compiles on the existing ue4-docker image on this host earlier today, so the problem wasn't affecting at least our existing CI pipeline, just when trying to build a new image.

**Comment by TBBle** [comment]
A new update today, the [issue's KB page](https://support.microsoft.com/en-au/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t) now specifies that it's 32-bit binaries that silently fail (which is why our existing CI pipelines were unaffected) and that they've released new container base images to address the images.

It's not clear from the text if the new container base images, e.g. 10.0.17763.1040 for ltsc2019, fail when used with older host versions, but I assume since they say the floating tags will be pointed at the Feb 18 builds, that they're safe to use with January and older hosts.

No new builds of <https://mcr.microsoft.com/v2/dotnet/framework/sdk/tags/list> yet though, based on the timestamps. I also don't see the new images on <https://mcr.microsoft.com/v2/windows/servercore/tags/list>. I wonder if the update was posted before the images were pushed...

**Comment by TBBle** [comment]
Sadly, new container on old host suffers the same issue, at least with the chocolatey installer, so it's still awful and messy and a hard ABI break.

## Host version
```
PS C:\Users\localadmin> cmd
Microsoft Windows [Version 10.0.17763.973]
(c) 2018 Microsoft Corporation. All rights reserved.

```

## New container
```
PS C:\Users\localadmin> docker run --rm -it mcr.microsoft.com/windows/servercore:ltsc2019
```
```
Microsoft Windows [Version 10.0.17763.1040]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.We
bClient).DownloadString('https://chocolatey.org/install.ps1'))
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.15.
Downloading 7-Zip commandline tool prior to extraction.
Extracting C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall...
Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install again. Error: 7-Zip signalled an unknown error (code -1073741511)
At line:220 char:15
+ ...   default { throw "$errorMessage 7-Zip signalled an unknown error (co ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to unzip...de -1073741511):String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install again. Error: 7-Zip signalled an unknown error (code
    -1073741511)

PS C:\> C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall\7za.exe
PS C:\> C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall\7za.exe --help
PS C:\> exit

C:\>exit
```
