### ISSUE TITLE
Unable to read askpass

### ISSUE THREAD

**Issue by Ludea** [adamrehn/ue4-docker#7]
The script build successfully the prerequies container.
But the last step (12) of the second container is failing. 
The error is : `unable to read askpass response from 'C:\git-credential-helper.bat`
So the build stop at this step

**Comment by Ludea** [comment]
I see this https://github.com/adamrehn/ue4-docker/blob/master/README.md#troubleshooting-common-issues
it is a firewall issue

**Comment by mareyes208** [comment]
JFYI - if anyone else is finding this issue - README.md (for this issue) moved here:
https://docs.adamrehn.com/ue4-docker/building-images/troubleshooting-build-issues#cloning-the-unrealengine-git-repository-fails-with-the-message-error-unable-to-read-askpass-response-from-cgit-credential-helperbat-for-windows-containers-or-tmpgit-credential-helpersh-for-linux-containers
