### ISSUE TITLE
Unable to build 4.24.3 on Windows and also building build-prerequisites

### ISSUE THREAD

**Issue by galeone** [adamrehn/ue4-docker#73]
```
ue4-docker version:         0.0.58 (latest available version is 0.0.58)
Operating system:           Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1039)
Docker daemon version:      19.03.5
NVIDIA Docker supported:    No
Maximum image size:         200GB
Available disk space:       629.78 GiB
Total system memory:        31.89 GiB physical, 43.36 GiB virtual
Number of processors:       20 physical, 40 logical
```

Hi, I'm trying to build a custom build version of the engine (some small change), using ue4docker-build:

```
ue4-docker.exe build custom:4.24.3 -repo=https://custom.repo/UnrealEngine.git -branch="4.24" --exclude debug --exclude templates --rebuild --pull-prerequisites
```

And this is the error I get

```
[ue4-docker build] Building image "adamrehn/ue4-engine:4.24.3-ltsc2019"...
Sending build context to Docker daemon  3.072kB
Step 1/8 : ARG NAMESPACE
Step 2/8 : ARG TAG
Step 3/8 : ARG PREREQS_TAG
Step 4/8 : FROM ${NAMESPACE}/ue4-source:${TAG}-${PREREQS_TAG}
 ---> e259007d2ddd
Step 5/8 : RUN GenerateProjectFiles.bat && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Running in 79a57e58896c
Setting up Unreal Engine 4 project files...

GenerateProjectFiles ERROR: It looks like you're missing some files that are required in order to generate projects.  Please check that you've downloaded and unpacked the engine source code, binaries, content and third-party dependencies before running this script.

Press any key to continue . . .
The command 'cmd /S /C GenerateProjectFiles.bat && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-engine:4.24.3-ltsc2019".
```

Moreover, I tried to remove the `--pull-prerequisites` flag from the CLI, and I'm also unable to build the build-prerequisites image

```
[ue4-docker build] Building image "adamrehn/ue4-build-prerequisites:ltsc2019"...
Sending build context to Docker daemon  1.849MB
Step 1/27 : ARG BASEIMAGE
Step 2/27 : FROM ${BASEIMAGE} AS dlls
 ---> 1afb4e8593d8
Step 3/27 : SHELL ["cmd", "/S", "/C"]
 ---> Using cache
 ---> c98fd22a1475
Step 4/27 : LABEL com.adamrehn.ue4-docker.sentinel="1"
 ---> Using cache
 ---> 28fa933f2d36
Step 5/27 : RUN mkdir C:\GatheredDlls && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 9b94cb19cb3d
Step 6/27 : RUN powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Running in e86caa32b6b4
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.15.
Downloading 7-Zip commandline tool prior to extraction.
Extracting C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall...
Unable to unzip package using 7zip. Perhaps try setting
$env:chocolateyUseWindowsCompression = 'true' and call install again. Error:
7-Zip signalled an unknown error (code -1073741502)
At line:220 char:15
+ ...   default { throw "$errorMessage 7-Zip signalled an unknown error (co ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to unzip...de -1073741
   502):String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to unzip package using 7zip. Perhaps try
   setting $env:chocolateyUseWindowsCompression = 'true' and call install aga
  in. Error: 7-Zip signalled an unknown error (code -1073741502)

The command 'cmd /S /C powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-build-prerequisites:ltsc2019".
```

Thank you again for this project :+1:

**Comment by adamrehn** [comment]
I strongly suspect this is related to [the Windows containers bug that causes 32-bit applications to fail silently](https://support.microsoft.com/en-au/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t), which was mentioned in #69. I'll investigate this as soon as I get the chance and determine which system configurations reproduce the problem.

**Comment by galeone** [comment]
Yes, it looks very related. The last error reported is the very same error (that I thought it was a 7-zip/choco issue), but still, I cannot understand in which way this is related to the GenerateProjectFiles error, that checks if an executable is present. Do you think that because of this bug the executable is not generated?

**Comment by adamrehn** [comment]
That error is [triggered if the Engine's binary dependencies haven't been downloaded](https://github.com/EpicGames/UnrealEngine/blob/4.24.3-release/Engine/Build/BatchFiles/GenerateProjectFiles.bat#L25), so it's possible that the `GitDependencies.exe` tool is failing to download things correctly, perhaps due to being a 32-bit application itself.

**Comment by galeone** [comment]
I'm still trying to figure out how to solve this problem, and from what I see the ue4 images depend on images of the .net  SDK 4.7 - that from what I see here  (https://hub.docker.com/_/microsoft-dotnet-framework-sdk/) are not upgraded with the February patch, and thus having an host with this patch, but a container without this patch can (I guess) cause incompatibility.

Do you think that it is feasible to upgrade the Docker images of unreal, to depend on the .net SDK 4.8 instead? (it look they updated only that SDK version)

**Comment by galeone** [comment]
Update: yes we can, I tried and I can build the images and use them without any problem. I open a merge request

**Comment by muit** [comment]
FYI: got this errors again with windows server 2019 freshly installed. Turns out the version distributed as ISO is outdated (17763.700 more or less). After updating it to 17763.1637 everything went smoothly.

Maybe worth adding to the docs

**Comment by adamrehn** [comment]
@muit I've added [a note to the troubleshooting section of the docs](https://docs.adamrehn.com/ue4-docker/building-images/troubleshooting-build-issues#building-the-ue4-build-prerequisites-image-fails-with-an-unknown-error) to cover this. The irony is not lost on me that I'm recommending that users install all available Windows updates when [it was a security patch that introduced the bug in the first place](https://support.microsoft.com/en-au/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t), of course.
