### ISSUE TITLE
Niagara PDB not being truncated

### ISSUE THREAD

**Issue by ShiroiKuma** [adamrehn/ue4-docker#75]
```
ue4-docker version:         0.0.59 (latest available version is 0.0.59)
Operating system:           Windows Server 2019 Standard Version 1809 (OS Build 17763.1131)
Docker daemon version:      19.03.5
NVIDIA Docker supported:    No
Maximum image size:         200GB
Available disk space:       303.06 GiB
Total system memory:        8 GiB physical, 14.58 GiB virtual
Number of processors:       8 physical, 8 logical
```

`ue4-docker build 4.24.3 --exclude debug --exclude templates
`

re-exec error: exit status 1: output: write \\?\C:\ProgramData\docker\tmp\hcs386473783\Files\UnrealEngine\LocalBuilds\InstalledDDC\Engine\Plugins\FX\HoudiniNiagara\Binaries\Win64\UE4Editor-HoudiniNiagaraEditor.pdb: There is not enough space on the disk.
[ue4-docker build] Error: failed to build image "adamrehn/ue4-minimal:4.24.3-ltsc2019".

Look's like the Niagra PDB's are not being truncated properly, but earlier on it did tell me it truncated it.

Truncating PDB file C:\UnrealEngine\LocalBuilds\Engine\Windows\Engine\Plugins\FX\HoudiniNiagara\Binaries\Win64\UE4Editor-HoudiniNiagara.pdb...
Truncating PDB file C:\UnrealEngine\LocalBuilds\Engine\Windows\Engine\Plugins\FX\HoudiniNiagara\Binaries\Win64\UE4Editor-HoudiniNiagaraEditor.pdb...

However, that appears to be a different path.

**Comment by adamrehn** [comment]
If the output indicates that the PDB files were truncated and you didn't [see a warning about failing to truncate them](https://github.com/adamrehn/ue4-docker/blob/v0.0.59/ue4docker/dockerfiles/ue4-minimal/windows/exclude-components.py#L32) then they will have been truncated correctly. The path in the error message is just the storage location on the host system, it's equivalent to the container path listed in your PDB truncation output. I strongly suspect that the real issue is this:

```
Available disk space:       303.06 GiB
```

If this was the amount of free disk space before you started the build then it's very likely you actually did run out of disk space and it just happened to be copying a truncated PDB file at the time. As stated in [the ue4-docker docs](https://adamrehn.com/docs/ue4-docker), 500GiB is the minimum recommended amount of disk space required for building Windows container images.

If you want to verify whether you're actually running out of disk space, you can [enable system resource monitoring](https://adamrehn.com/docs/ue4-docker/building-images/advanced-build-options#enabling-system-resource-monitoring-during-builds) using the `--monitor` flag, which will display the amount of free disk space at intervals throughout the build. If it trends towards zero during the failing step then a lack of disk space is to blame.

**Comment by ShiroiKuma** [comment]
I've been re-running a 2nd time overnight with `--monitor` to confirm that. This was running on a 640GB of free space before the build started (the same server as all my previous tests)

**Comment by adamrehn** [comment]
A slight addendum to my previous comment: taking a closer look at those paths, there actually is a minor difference (`UnrealEngine\LocalBuilds\InstalledDDC\Engine` vs `UnrealEngine\LocalBuilds\Engine\Windows\Engine`) that I overlooked before. (Evidently my brain isn't at its sharpest first thing on a Saturday morning.)

This means that the files the error message is referring to are actually temporary files generated during the creation of the Installed Build of the Engine, rather than the completed files that then get copied into the next stage of the multi-stage image build. My diagnosis remains unchanged (I believe you genuinely ran out of disk space), but what this does mean is that those temporary files are not getting cleaned up automatically like I thought they were, and there may be an opportunity to reduce the amount of disk space required for building the images by explicitly deleting those files before they get committed to the filesystem layer. I'll have a look into this.

**Comment by adamrehn** [comment]
Right, I've added commands to delete those temporary files in commit 31d81a3, which should hopefully reduce the amount of disk space that gets used during the build process. I'll perform some tests to confirm this.

**Comment by ShiroiKuma** [comment]
During the monitor test, it did get close to filling the machine's HDD, but at the point of failure, there was 302GB available. I'll try modifying with the above commit locally and see if that helps.

```
[ue4-docker build] [2020-03-21 01:50:45] [Available disk: 13.22 GiB] [Available memory: 5.40 GiB physical, 11.86 GiB virtual] [CPU usage: 16.80%]
[ue4-docker build] [2020-03-21 01:51:05] [Available disk: 12.56 GiB] [Available memory: 5.47 GiB physical, 11.87 GiB virtual] [CPU usage: 23.20%]
[ue4-docker build] [2020-03-21 02:00:23] [Available disk: 116.80 GiB] [Available memory: 5.27 GiB physical, 11.62 GiB virtual] [CPU usage: 23.40%]
[ue4-docker build] [2020-03-21 02:00:43] [Available disk: 119.12 GiB] [Available memory: 5.26 GiB physical, 11.62 GiB virtual] [CPU usage: 26.20%]
[ue4-docker build] [2020-03-21 02:01:03] [Available disk: 120.81 GiB] [Available memory: 5.29 GiB physical, 11.62 GiB virtual] [CPU usage: 24.90%]
[ue4-docker build] [2020-03-21 02:01:23] [Available disk: 121.86 GiB] [Available memory: 5.23 GiB physical, 11.55 GiB virtual] [CPU usage: 24.40%]
[ue4-docker build] [2020-03-21 02:01:43] [Available disk: 122.19 GiB] [Available memory: 5.22 GiB physical, 11.55 GiB virtual] [CPU usage: 24.60%]
[ue4-docker build] [2020-03-21 02:02:03] [Available disk: 122.80 GiB] [Available memory: 5.21 GiB physical, 11.53 GiB virtual] [CPU usage: 23.50%]
[ue4-docker build] [2020-03-21 02:02:23] [Available disk: 122.98 GiB] [Available memory: 5.20 GiB physical, 11.53 GiB virtual] [CPU usage: 23.00%]
[ue4-docker build] [2020-03-21 02:02:43] [Available disk: 137.30 GiB] [Available memory: 5.27 GiB physical, 11.61 GiB virtual] [CPU usage: 24.10%]
[ue4-docker build] [2020-03-21 02:03:03] [Available disk: 141.94 GiB] [Available memory: 5.27 GiB physical, 11.61 GiB virtual] [CPU usage: 23.90%]
[ue4-docker build] [2020-03-21 02:03:23] [Available disk: 149.57 GiB] [Available memory: 5.43 GiB physical, 11.79 GiB virtual] [CPU usage: 30.30%]
[ue4-docker build] [2020-03-21 02:03:43] [Available disk: 149.57 GiB] [Available memory: 5.43 GiB physical, 11.79 GiB virtual] [CPU usage: 27.30%]
[ue4-docker build] [2020-03-21 02:04:03] [Available disk: 149.57 GiB] [Available memory: 5.43 GiB physical, 11.79 GiB virtual] [CPU usage: 27.10%]
[ue4-docker build] [2020-03-21 02:04:23] [Available disk: 149.57 GiB] [Available memory: 5.43 GiB physical, 11.80 GiB virtual] [CPU usage: 28.30%]
[ue4-docker build] [2020-03-21 02:04:43] [Available disk: 149.57 GiB] [Available memory: 5.42 GiB physical, 11.80 GiB virtual] [CPU usage: 28.90%]
[ue4-docker build] [2020-03-21 02:05:03] [Available disk: 149.57 GiB] [Available memory: 5.43 GiB physical, 11.80 GiB virtual] [CPU usage: 28.80%]
[ue4-docker build] [2020-03-21 02:05:23] [Available disk: 149.57 GiB] [Available memory: 5.46 GiB physical, 11.81 GiB virtual] [CPU usage: 28.10%]
[ue4-docker build] [2020-03-21 02:05:43] [Available disk: 149.57 GiB] [Available memory: 5.43 GiB physical, 11.82 GiB virtual] [CPU usage: 28.10%]
[ue4-docker build] [2020-03-21 02:06:03] [Available disk: 181.61 GiB] [Available memory: 5.44 GiB physical, 11.82 GiB virtual] [CPU usage: 25.30%]
[ue4-docker build] [2020-03-21 02:06:23] [Available disk: 216.08 GiB] [Available memory: 5.44 GiB physical, 11.82 GiB virtual] [CPU usage: 23.90%]
[ue4-docker build] [2020-03-21 02:06:43] [Available disk: 236.79 GiB] [Available memory: 5.45 GiB physical, 11.82 GiB virtual] [CPU usage: 23.80%]
[ue4-docker build] [2020-03-21 02:07:03] [Available disk: 249.55 GiB] [Available memory: 5.45 GiB physical, 11.83 GiB virtual] [CPU usage: 24.10%]
[ue4-docker build] [2020-03-21 02:07:23] [Available disk: 263.15 GiB] [Available memory: 5.46 GiB physical, 11.82 GiB virtual] [CPU usage: 24.00%]
[ue4-docker build] [2020-03-21 02:07:43] [Available disk: 266.71 GiB] [Available memory: 5.46 GiB physical, 11.82 GiB virtual] [CPU usage: 23.80%]
[ue4-docker build] [2020-03-21 02:08:03] [Available disk: 269.07 GiB] [Available memory: 5.46 GiB physical, 11.82 GiB virtual] [CPU usage: 24.00%]
[ue4-docker build] [2020-03-21 02:08:24] [Available disk: 270.55 GiB] [Available memory: 5.44 GiB physical, 11.82 GiB virtual] [CPU usage: 24.20%]
[ue4-docker build] [2020-03-21 02:08:44] [Available disk: 271.38 GiB] [Available memory: 5.45 GiB physical, 11.82 GiB virtual] [CPU usage: 23.90%]
[ue4-docker build] [2020-03-21 02:09:04] [Available disk: 271.93 GiB] [Available memory: 5.45 GiB physical, 11.82 GiB virtual] [CPU usage: 24.00%]
[ue4-docker build] [2020-03-21 02:09:24] [Available disk: 272.26 GiB] [Available memory: 5.45 GiB physical, 11.82 GiB virtual] [CPU usage: 24.20%]
[ue4-docker build] [2020-03-21 02:09:44] [Available disk: 272.81 GiB] [Available memory: 5.46 GiB physical, 11.82 GiB virtual] [CPU usage: 24.30%]
[ue4-docker build] [2020-03-21 02:10:04] [Available disk: 288.18 GiB] [Available memory: 5.45 GiB physical, 11.82 GiB virtual] [CPU usage: 24.00%]
[ue4-docker build] [2020-03-21 02:10:24] [Available disk: 302.59 GiB] [Available memory: 5.45 GiB physical, 11.83 GiB virtual] [CPU usage: 26.40%]
re-exec error: exit status 1: output: write \\?\C:\ProgramData\docker\tmp\hcs191087299\Files\UnrealEngine\LocalBuilds\InstalledDDC\Engine\Plugins\Media\MediaIOFramework\Binaries\Win64\UE4Editor-MediaIOCore.pdb: There is not enough space on the disk.
[ue4-docker build] Error: failed to build image "adamrehn/ue4-minimal:4.24.3-ltsc2019".
```

**Comment by adamrehn** [comment]
I've finished testing the modifications, and the size savings are fairly significant. Depending on the configuration (Windows/Linux, version of UE4, number of enabled RHIs, etc.) the intermediate filesystem layer for that `RUN` directive is reduced from between ~10GB to ~40GB, with the most noticeable difference observed for Windows containers. That change is now live in ue4-docker version 0.0.60.

Hopefully the reduced space requirements should allow the build to complete successfully on your system without running out of disk space.

**Comment by ShiroiKuma** [comment]
It worked fine now, and oddly enough 15 hrs faster than normal, which is odd. I put that down to server load.

The available space didn't drop below 60gb spare this time around, so it definitely helped a lot.

One last question while we're on the topic of space. Any idea what these linkering <none> images are for? Might be something extra needing some cleanup? I have these <none>'s on my Linux server too.

```
adamrehn/ue4-full                        4.24.3                           c472fb0d7da6        About an hour ago   39.1GB
adamrehn/ue4-full                        4.24.3-ltsc2019                  c472fb0d7da6        About an hour ago   39.1GB
<none>                                   <none>                           7cbbfadbdbfa        About an hour ago   77.8GB
adamrehn/ue4-minimal                     4.24.3                           6affdd793644        2 hours ago         38.1GB
adamrehn/ue4-minimal                     4.24.3-ltsc2019                  6affdd793644        2 hours ago         38.1GB
<none>                                   <none>                           4504a8eaf172        2 hours ago         209GB
adamrehn/ue4-engine                      4.24.3                           f22cb95f989e        18 hours ago        131GB
adamrehn/ue4-engine                      4.24.3-ltsc2019                  f22cb95f989e        18 hours ago        131GB
adamrehn/ue4-source                      4.24.3                           1b9e0cc0d811        21 hours ago        77GB
adamrehn/ue4-source                      4.24.3-ltsc2019                  1b9e0cc0d811        21 hours ago        77GB
adamrehn/ue4-build-prerequisites         ltsc2019                         0bb647cc020a        23 hours ago        26GB
<none>                                   <none>                           dcc9c297ff59        24 hours ago        11.4GB
mcr.microsoft.com/dotnet/framework/sdk   4.8-windowsservercore-ltsc2019   930efd250e65        3 days ago          9.96GB
```

**Comment by adamrehn** [comment]
Excellent, I'm glad that fixed it. The images listed with `<none>` in the tag column are the intermediate stages from the [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) used by the build prerequisites, minimal and full images. Those can be safely cleaned up by running `docker system prune`, which will also remove the related build cache data, or by running the [ue4-docker clean](https://adamrehn.com/docs/ue4-docker/commands/clean) command, which provides more fine-grained control over what data gets removed.
