### ISSUE TITLE
Help needed in Pixel Streaming

### ISSUE THREAD

**Issue by plushpluto** [adamrehn/ue4-docker#78]
I am trying to stream a community project for a local montessori school nearby. It is compiled using UE4-4.23.1. I tried using ue4-docker (your source). It won't help, since the docker was preprogrammed for 4.20.1. As per your suggestion in the documentation, I am trying https://adamrehn.com/articles/pixel-streaming-in-linux-containers/. I am stuck here as well. In short, I am trying to recreate your youtube demo, but the content is for the kids here. 

Status:

- Took the 4.23.1 source from your repo.
- Used my content.
- Compiled it.
- I am stuck here. Should I follow the multi-stage build? I am just a new bee for all these things. Any help!!!

**Comment by plushpluto** [comment]
Opening the same issue in https://github.com/adamrehn/pixel-streaming-linux/issues/8 as well. Don't know which one you will see first.

**Comment by adamrehn** [comment]
Closing this issue and continuing the discussion at <https://github.com/adamrehn/pixel-streaming-linux/issues/8>
