### ISSUE TITLE
[Questions] botocore warning, ddc, build space

### ISSUE THREAD

**Issue by ShiroiKuma** [adamrehn/ue4-docker#80]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.62 (latest available version is 0.0.62)
Operating system:           Windows Server 2019 Standard Version 1809 (OS Build 17763.1158)
Docker daemon version:      19.03.5
NVIDIA Docker supported:    No
Maximum image size:         200GB
Available disk space:       594.35 GiB
Total system memory:        8 GiB physical, 13.44 GiB virtual
Number of processors:       8 physical, 8 logical
```

Just building things on my R710 during this crisis and having more time available than normal and have a few questions.

1) Building just now with `ue4-docker build 4.24.3 --exclude debug --exclude templates --no-engine` and noticed the following warning when ` pip install "ue4cli>=0.0.41" "conan-ue4cli>=0.0.21" ue4-ci-helpers --no-warn-script-location` executed there was a pip warning.

"botocore 1.15.46 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible."

I'm not sure if you are using features that depend on that though, or if it's safe to ignore.

2) I noticed a new exclude DDC option in the commits, but this isn't documented on the website docs yet. Oversight or not yet tested for release?

3) I'm curious where we need free space to build these images. Is **ALL** space used, actually within Docker? If so, theoretically I could use a C: drive of 64GB but a D: drive of 512GB (would make managing a VM environment a bit easier)

**Comment by adamrehn** [comment]
- Regarding the `botocore` requirement conflict, the `ue4-ci-helpers` package only uses a [very small subset of the AWS functionality from botocore](https://github.com/adamrehn/ue4-ci-helpers/blob/master/ue4helpers/AWSUtils.py) and none of that involves documentation processing, so it should be fine to ignore that warning.

- Regarding the DDC exclusion option, I'd simply forgotten to add that to the docs, so thankyou for reminding me. [That's documented now.](https://adamrehn.com/docs/ue4-docker/building-images/advanced-build-options#excluding-engine-components-to-reduce-the-final-image-size)

- The [ridiculous amount of space](https://adamrehn.com/docs/ue4-docker/read-these-first/large-container-images-primer#disk-space-consumption-during-the-build-process) used by Docker during the image builds is scratch space for the filesystem layers, which I suspect is most likely stored in Docker's data directory alongside the committed filesystem layers themselves. You can control the location of the data directory by [modifying the Docker daemon's configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file) and setting the value of the `data-root` configuration key, which can be useful for moving Docker's data files to another drive if your system drive is a bit small. (In fact, the `Available disk space` entry reported in the info output is actually [the amount of free space on whichever drive you've configured Docker to use for its data directory](https://github.com/adamrehn/ue4-docker/blob/v0.0.62/ue4docker/info.py#L27-L33).) Bear in mind that migrating the existing contents of the data directory to a new location can be problematic sometimes, so make sure you've backed up any important images first by either pushing them to container registries or exporting them to tarballs using the [docker save](https://docs.docker.com/engine/reference/commandline/save/) command.
