### ISSUE TITLE
Unblacklist Windows 1903/1909 (with new-enough Docker Engine)

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4-docker#81]
Per https://github.com/docker/for-win/issues/4100#issuecomment-581043061, [Docker 19.03.6](https://github.com/docker/engine/pull/429) contains the [work-around](https://github.com/microsoft/hcsshim/pull/718) for the [Windows HCS issue](https://github.com/microsoft/hcsshim/issues/708) that prevents larger-than-default container sizes in the Windows 1903/1909 kernel.

I've tested the workaround [on my desktop machine at home](https://github.com/docker/for-win/issues/4100#issuecomment-626283916), but not with ue4-docker, as my ue4-docker build host at work is ltsc2019. I see no reason why it wouldn't work in ue4-docker though...

So we could remove the blacklisting of those base versions, and either check or document that the Docker version in-use is new-enough to have that fix, similarly for the original 8GB-file issue.

That is assuming I'm correct that the 1903/1909 black-listing is because of the storage-opts bug... If it was something else, disregard this. ^_^

**Comment by adamrehn** [comment]
Excellent, running `ue4-docker diagnostics maxsize` on my machine with Windows 10 version 1909 and Docker Engine 19.03.8 shows the diagnostic passing successfully. Commit with an updated check incoming...

**Comment by adamrehn** [comment]
Fix is live in ue4-docker version 0.0.65.
