### ISSUE TITLE
Add Windows 10/Server 2004 support

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4-docker#88]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.68 (latest available version is 0.0.68)
Operating system:           Windows 10 Pro Version 2004 (OS Build 19041.329)
Docker daemon version:      19.03.8
NVIDIA Docker supported:    No
Maximum image size:         20GB
Available disk space:       37.72 GiB
Total system memory:        15.96 GiB physical, 22.99 GiB virtual
Number of processors:       4 physical, 8 logical
```

I noticed while using `ue4-docker diagnostics 8gig` to check if https://github.com/moby/moby/issues/40444 was fixed, that it used `BASETAG=1909`.

It looks like it works to add 2004 to `_validTags`, `getReleaseBaseTag` and bump `_latestReleaseBuild` to 19041. Sadly, it seems Windows 10 2004 also fails the 8gig test, so I assume Windows Server 2004 will be the same.

**Comment by adamrehn** [comment]
Thanks for reminding me, relevant changes now done in 5b8b0ce.

Damn, I thought we were finally past that bug. I'll run some tests under Windows Server version 2004 to confirm.

**Comment by adamrehn** [comment]
Testing under Windows Server version 2004 confirms the failure of the 8gig diagnostic. (On a related note, I've added new flags in commit 0db3548 to control base image tag and isolation mode, and the `-m 4GiB` build argument now only gets passed to Docker when using Hyper-V isolation mode.) Thanks for [reporting this](https://github.com/microsoft/Windows-Containers/issues/43) to the Windows Containers platform team, hopefully they can track down the underlying cause of the issue in the HCS.

Support for Windows version 2004 is now live in ue4-docker version 0.0.69.
