### ISSUE TITLE
Running in Docker or Singularity?

### ISSUE THREAD

**Issue by jeffreyng99** [adamrehn/ue4-docker#89]
Hello, first off thank you for creating this tool. It is extremely helpful. I was wondering if it possible to run the image with just plain Docker or Singularity? I ask this because when trying to start the binary in Docker, it throws an error. 

System: Ubuntu 18.04
Image: adamrehn/ue4-engine:4.19.2-cudagl10.0 & adamrehn/ue4-engine:4.24.0-cudagl10.0 

`ue4-docker info`:
ue4-docker version:         0.0.69 (latest available version is 0.0.69)
Operating system:           Linux (Ubuntu 18.04.4 LTS, 5.4.0-42-generic)
Docker daemon version:      19.03.12
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       293.83 GiB
Total system memory:        31.35 GiB physical, 52.15 GiB virtual
Number of processors:       6 physical, 12 logical

**Comment by adamrehn** [comment]
Apologies for the delay in responding to this issue, I've been inordinately busy over the past couple of months and I'm only now making my way through my GitHub backlog.

Yes, the container images built by ue4-docker can be run using plain Docker or any other OCI-compliant container runtime. However, if you require GPU acceleration (e.g. for running the Unreal Engine without the `-nullrhi` flag) then you will need to use Docker [with the NVIDIA Container Toolkit](https://unrealcontainers.com/docs/concepts/nvidia-docker).
