### ISSUE TITLE
ue4-Build error '4.23.1' for Ubuntu

### ISSUE THREAD

**Issue by Jggggg** [adamrehn/ue4-docker#95]
I have a ue4-build error for 4.23.1 on Ubuntu

  ERROR: unable to build: no compatible clang version found please run setup.sh

I tried to reload clang.and it didn't work

**Comment by TBBle** [comment]
Probably the same as #94... Apparently (https://github.com/adamrehn/ue4-docker/issues/94#issuecomment-698582793) it was a problem on Epic's end that has since been resolved.

**Comment by oxfowww** [comment]
Yeah.I solved it.but I do my best to overwrite 4.24 .any suggestion?

**Comment by adamrehn** [comment]
Closing as per the resolution to #94.
