### ISSUE TITLE
4.24 Linux ue4-docker build error

### ISSUE THREAD

**Issue by oxfowww** [adamrehn/ue4-docker#98]
Thanks for your project.
I meet some trouble, the 4.24-pixelstreaming, Windows To Linux; 
And I am looking forward to your reply，Thanks!!

Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.71 (latest available version is 0.0.71)
Operating system:           Linux (Ubuntu 18.04.2 LTS, 4.18.0-15-generic)
Docker daemon version:      19.03.12
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       198.95 GiB
Total system memory:        7.7 GiB physical, 2 GiB virtual
Number of processors:       2 physical, 4 logical
```
Input Command:

```
sudo ue4-docker build custom:4.24.0-pixelstreaming -repo=https://github.com/oxfowww/PixelTest.git -branch=master
```
Error:
```
Step 28/37 : RUN ./Setup.sh && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in 5d96cd2a011c
/bin/sh: 1: ./Setup.sh: Permission denied
The command '/bin/sh -c ./Setup.sh && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''' returned a non-zero code: 126
[ue4-docker build] Error: failed to build image "adamrehn/ue4-source:4.24.0-pixelstreaming-opengl".
```
And the Log:
[log.txt](https://github.com/adamrehn/ue4-docker/files/5232130/log.txt)

**Comment by TBBle** [comment]
Is there any chance `Setup.sh` in your Git repo has lost its 'executable' flag during your customisations?

If you look at https://github.com/oxfowww/PixelTest/blob/master/Setup.sh it should say "Executable File" in the top-left of the file, similar to the below:
![image](https://user-images.githubusercontent.com/138397/94356106-0c074c80-00ce-11eb-8293-7184f0361436.png)

**Comment by adamrehn** [comment]
I agree with @TBBle, the most likely cause is a file permissions issue in your custom branch of the Unreal Engine, rather than a problem with ue4-docker.
